---
title: "学術論文"
---


### in press

- [34] Wang, K., Goldenberg, A., Dorison, C., Miller, J. K. P., Uusberg, A., Lerner, J. S., Gross, J., Marcu, G. M., Agadullina, E., Adamkovic, M., Roczniewska, M., Kassianos, A., Dursun, P., Arinze, A. I., Arinze, N. C., Ogbonnaya, C., Ndukaihe, I. L. G., Dalgar, I., Akkas, H., Macapagal, P. M. L., Lewis, S., Metin-Orta, I., Willis, M., Santos, A. C., Mokady, A., Reggev, N., Vasilev, M. R., Nock, N. L., Parzuchowski, M., Barría, M. E., Vranka, M. A., Ropovik, I., Yao, X., Becker, M., Manunta, E., Kaminski, G., Findor, A., Lewis, D. M. G., Aruta, J. J. B. R., Zickfeld, J., Vásquez, J. C., Pronizius, E., Lamm, C., Li, R., Valentova, J. V., Mioni, G., Cellini, N., Chen, S.-C., Moon, K., Azab, H., Todsen, A. L., van Schie, K., Bavolar, J., Warmelink, L., Ross, R. M., Stephen, I. D., Hostler, T., McCarthy, R. J., Grano, C., Singh Solorzano, C., Kácha, O., Arvanitis, A., Xiao, Q., Cárcamo, R., Zorjan, S., Tajchman, Z. J., Vilares, I., Pavlacic, J. M., Kunst, J. R., Tamnes, C. K., Atari, M., Sharifian, M., Hricova, M., Kačmár, P., Rahal, R.-M., Zakharov, I., Koehn, M. A., Esteban Serna, C., Hajdu, N., Calin-Jageman, R., Krafnick, A. J., Očovaj, S. B., Khosla, M., Urban, J., Boudesseul, J., Silva, J., Martončik, M., Šakan, D., Kuzminska, A., Djordjevic, J. M., Almeida, I. A. T., Lazarevic, L. B., Manley, H., Zambrano, D., Monteiro, R. P., Musser, E. D., Dunleavy, D. J., Godbersen, H., Ruiz-Fernandez, S., Reeck, C., Batres, C., Azevedo, F., Alvarez, D. S., Chen, Z., Verbruggen, F., Ziano, I., Tümer, M., Dubrov, D., Karababa, A., del Carmen, M., Aberson, C., Moller, A. C., Hubená, B., Ceary, C., Singer, G. A., Perillo, J. T., Ballantyne, T., Du, H., Pit, I. L., Hruška, M., Sousa, D., Aczel, B., Szaszi, B., Barzykowski, K., Micheli, L., Zsido, A. N., Paruzel-Czachura, M., Bialek, M., Kowal, M., Sorokowska, A., Misiak, M., Arriaga, P., Oliveira, R. A., Vaughn, L. A., Szwed, P., Kossowska, M., Kielińska, J., Antazo, B. G., Stieger, S., Nilsonne, G., simonovic, N., Taber, J. M., Gourdon-Kanhukamwe, A., Domurat, A., Ihaya, K., Yamada, Y., Urooj, A., Gill, T., Bylinina, L., Baklanova, E., Albayrak-Aydemir, N., Kappes, H. B., Gjoneska, B., House, T., Berkessel, J., Muda, R., Chopik, W. J., Çoksan, S., Seehuus, M., Khaoudi, A., Azouaghe, S., Arabi, K. A. E., Djamai, I., Wilson, J. P., Adiguzel, A., Kocalar, H. E., Norton, J., Papadatou-Pastou, M., Evans, K., Chuan-Peng, H., De la Rosa-Gomez, A., Ankushev, V., Bogatyreva, N., Grigoryev, D., Ivanov, A., Prusova, I., Romanova, M., Sarieva, I., Terskova, M., Hristova, E., Janak, A., Schei, V., Sverdrup, T. E., Askelund, A. D., Collins, W. M., Boucher, L., Ouherrou, N., Schrötter, J., Bokkour, A., Say, N., Sinkolova, S., Janjić, K., Stojanovska, D., Bijlstra, G., Mosannenzadeh, F., Reips, U.-D., Baskin, E., Ishkhanyan, B., Czamanski-Cohen, J., Dixson, B., Moreau, D., Sutherland, C., Noone, C., Anne, M., Janssen, S. M. J., Fu, C. H., Majeed, N. M., Kunisato, Y., Daches, S., Hartanto, A., Vdovic, M., Forbes, P., Kamburidis, J., Rachev, N. R., Stoyanova, A., Marinova, E., Schmidt, K., Suchow, J. W., Koptjevskaja-Tamm, M., Jernsäther, T., Olofsson, J., Bialobrzeska, O., Marszalek, M., Tatachari, S., Afhami, R., Law, W., Zuro, B., Van Doren, N., Soto, J., Searston, R. A., Miranda, J. F., Yeung, S. K., Krupić, D., Jaeger, B., Ren, D., Pfuhl, G., Klevjer, K., Vally, Z., Vargas-Nieto, J. C., Corral-Frías, N. S., Frias-Armenta, M., Lucas, M. Y., Torres, A. O., Toro, M., Vega, D., Solas, S. Á., Vilar, R., Massoni, S., Reyna, C., Pöntinen, S. J., Adetula, G. A., Foroni, F. P., Kurfali, M. A., Braun Kohlová, M., Harutyunyan, M., Landry, A. T., Ortiz, M., Voracek, M., Grinberg, M., Vintr, J., Kaliska, L., Pourafshari, R., Geiger, S. J., Beitner, J., Szala, A., Anjum, G., von Bastian, C. C., Cohen, N., Kirgizova, K., Muminov, A., Butt, M. M., Lee, J. M., Charyate, A., Sacakli, A., Richard, K., Cyrus-Lai, W., Fedotov, M., Wielgus, M., Adamus, S., Mola, D., Correa, P. S., Belaus, A., Muchembled, F., Ribeiro, R. R., Abbas, N., Čadek, M., Messerschmidt, J., Adetula, A., Kadreva, V., Bran, A., Vaidis, D. C., Vieira, L., Coelho, G. L. H., Whitt, C. M., Tullett, A. M., Du, X., Volz, L., Sarioguz, E., Korbmacher, M., Lima, T., Ribeiro, M. F. F., Verharen, J., Karekla, M., Jaremka, L. M., Storage, D., Studzinska, A., Hanel, P. H. P., Holford, D. L., Sirota, M., Wolfe, K., Chiu, F., Theodoropoulou, A., Ahn, E. R., Lin, Y., Westgate, E. C., Hofer, G., Vezirian, K., Travaglino, G. A., Marko, D., Li, M., Torunsky, N., Manavalan, M., Song, X., Walczak, R. B., Zdybek, P., Dalla Rosa, A., Kozma, L., Alves, S. G., Correia, R., Pinto, I. R., Babincak, P., Baník, G., Varella, M. A. C., Uttley, J., Beshears, J., Thommesen, K. K., Behzadnia, B., Bradford, M., Geniole, S., Silan, M. A., Vilsmeier, J. K., Tran, U. S., Morales-Izquierdo, S., Mensink, M. C., Groyecka-Bernard, A., Sorokowski, P., Radtke, T., Özdoğru, A. A., Ishii, T., Wichman, A. L., Röer, J. P., Ostermann, T., Davis, W. E., Suter, L., Ferreira, A., Agesin, B. B., Rana, K., Eudave, L., Campos, O., Grzech, K., Hausman Ozery, D., Jackson, E. A., Jimenez-Leal, W., Krizanic, V., Garcia, E. O. L., Drexler, S. M., Jurković, A. P., Štrukelj, E., Antoniadi, M., Desai, K., Gialitaki, Z., Kushnir, E., Nadif, K., Bravo, O. N., Nauman, R., Oosterlinck, M., Pantazi, M., Pilecka, N., Szabelska, A., van Steenkiste, I. M. M., Filip, K., Bozdoc, A. I., Westerlund, M., Ahlgren, L., Wang, C., Levy, N. L., Beaudry, J. L., Samojlenko, L., Isager, P. M., Chou, W., Pálfi, B., Schmidt, N.-D., Ortiz, M. V., Czarnek, G., Jones, M., Berkessel, J. B., Iyer, A., Parashar, N., Bundt, C., Pineda, L. M. S., Thomas, A. G., Kung, F. Y. H., Balci, B. B., Flowe, H. D., Topor, M., Yu, K., Anton-Boicuk, L., Kurfalı, M., Antfolk, J., Damnjanović, K., Hoyer, K., Galindo-Caballero, O. J., Calderón Pérez, L., Delgado, G. J., Frizzo, T., Capizzi, M., Greenburgh, A., Bosma, M., Karaarslan, C., Allred, T. B., Colloff, M. F., Karashiali, C., Sunami, N., Habib, S., Hassan, W., Brohmer, H., Dujols, O., Feldman, G., Ahmed, A., Bosch, J., Bai, H., Friedemann, M., Rojas-Berscia, L. M., Maturan, P. L. G., Walasek, L., Adoric, V. C., Carpentier, J., Joy-Gaba, J. A., Zabel, C., Ebersole, C. R., Chartier, C. R., Mallik, P. R., Urry, H. L., Buchanan, E. M., Coles, N. A., Primbs, M., Basnight-Brown, D., IJzerman, H., Forscher, P. S., & Moshontz, H., (in press).
A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. 
Nature Human Behaviour.


### 2021

- [33] Shimono, Y., Hasegawa, A., Tsuchihara, K., Tanaka, K., Matsuda, Y., & Kunisato, Y.(2021) Longitudinal association between autistic traits and affinity for hikikomori in Japanese university students. Current Psychology. https://doi.org/10.1007/s12144-020-01287-x

- [32] van Doorn, J., van den Bergh, D., Dablander, F., van Dongen, N., Derks, K., Evans, N., Gronau, Q., Haaf, J., Kunisato, Y., Ly, A., Marsman, M., Sarafoglou, A., Stefan, A., & Wagenmakers, EJ.(2011) Strong public claims may not reflect researchers' private convictions. Significance, 18(1), 44-45.[Pre Print](https://psyarxiv.com/pc4ad/)


### 2020

- [31] Kato, A., Kunisato, Y., Katahira, K., Okimura, T., & Yamashita, Y. (2020) Computational Psychiatry Research Map (CPSYMAP): a New Database for Visualizing Research Papers. Frontiers in Psychiatry, 11, 1360.[Link](https://www.frontiersin.org/articles/10.3389/fpsyt.2020.578706/full)

- [30] Katahira, K., Kunisato, Y., Okimura, T., & Yamashita, Y. (2020) Retrospective surprise: A computational component for active inference. Journal of Mathematical Psychology, 96, 102347.  [Link](https://www.sciencedirect.com/science/article/abs/pii/S0022249620300286?dgcid=author)

- [29] Katahira, K., Kunisato, Y., Yamashita, Y., & Suzuki, S. (2020) Commentary: "A robust data-driven approach identifies four personality types across four large data sets". Frontiers in Big Data, 3(8). [Link](https://www.frontiersin.org/articles/10.3389/fdata.2020.00008/full)

### 2019

- [28] Nishiguchi, Y., Sakamoto, J., Kunisato, Y., & Takano, K. (2019) Linear Ballistic Accumulator Modeling of Attentional Bias Modification Revealed Disturbed Evidence Accumulation of Negative Information by Explicit Instruction. Frontiers in Psychology,10, 2447.  [Link](https://www.frontiersin.org/articles/10.3389/fpsyg.2019.02447/full)

- [27] Yokomitsu, K., Sakai, T., Irie, T., Tayama, J., Furukawa, H., Himachi, M., Kanazawa, J., Koda, M., Kunisato, Y., Matsuoka, H., Takada, T., Takahashi, F., Takahashi, T., & Osawa, K. (2019). Gambling symptoms, behaviors, and cognitive distortions in Japanese university students. Substance Abuse Treatment, Prevention, and Policy, 14, 51.  [Link](https://substanceabusepolicy.biomedcentral.com/articles/10.1186/s13011-019-0230-5)

- [26] Hasegawa, A., Somatori, K., Nishimura, H., Hattori, Y., & Kunisato, Y. (2019). Associations between self-reported impulsivity and a latent variable of impulsive action constructed from three laboratory tasks. Journal of Experimental Psychopathology, 10, 3. [Link](https://journals.sagepub.com/doi/full/10.1177/2043808719861894)


### 2018

- [25] Hasegawa, A., Kunisato, Y., Morimoto, H., Nishimura, H., & Matsuda, Y. (2018). Depressive rumination and urgency have mutually enhancing relationships but both predict unique variance in future depression: A longitudinal study. Cogent Psychology, 5: 1450919.ß [Link](https://www.tandfonline.com/doi/full/10.1080/23311908.2018.1450919)

- [24] Hasegawa, A., Kunisato, Y., Morimoto, H., Nishimura, H., & Matsuda, Y. (2018). How do rumination and social problem solving intensify depression? A longitudinal study. Journal of Rational-Emotive & Cognitive-Behavior Therapy, 36, 1, 28-46. [Link](https://link.springer.com/article/10.1007/s10942-017-0272-4)

- [23] Takagaki, K., Okamoto, Y., Jinnin, R., Mori, A., Nishiyama, Y., Yamamura, T., Yokoyama, S., Shiota, S., Okamoto, Y., Miyake, Y., Ogata, A., Kunisato, Y., Shimoda, H., Kawakami, N., Furukawa, T. A., & Yamawaki. (2018).  Enduring effects of a five-week behavioral activation program for subthreshold depression among late adolescents: an exploratory randomized controlled trial.  Neuropsychiatric Disease and Treatment , 14, 2633-2641. [Link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6186299/)

### 2017

- [22] Moriguchi, Y., Noda, T., Nakayashiki, K., Takata, Y., Setoyama, S., Kawasaki, S., Kunisato, Y., Mishima, K., Nakagome, K., Hanakawa, T. (2017). Validation of brain-derived signals in near-infrared spectroscopy through multivoxel analysis of concurrent functional magnetic resonance imaging. Human Brain Mapping, 38(10), 5274–5291.  [Link](https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.23734)

- [21] Yoshimura, S., Okamoto, Y., Matsunaga, M., Onoda, K., Okada, G., Kunisato, Y., Yoshino, A., Ueda, K., Suzuki, S., & Yamawaki, S. (2017). Cognitive behavioral therapy changes functional connectivity between medial prefrontal and anterior cingulate cortices, Journal of Affective Disorders, 15(208), 610-614. [Link](https://www.sciencedirect.com/science/article/abs/pii/S0165032716305195)
 
### 2016
 
- [20] Takagaki, K., Okamoto, Y., Jinnin, R., Mori, A., Nishiyama, Y., Yamamura, T., Yokoyama, S., Shiota, S., Okamoto, Y., Miyake, Y., Ogata, A., Kunisato, Y., Shimoda, H., Kawakami, N., Furukawa, A. T., & Yamawaki. (2016). Behavioral activation for late adolescents with subthreshold depression: a randomized controlled trial. European Child & Adolescent Psychiatry, 25(11), 1171-1182. [Link](https://link.springer.com/article/10.1007/s00787-016-0842-5)
 
- [19] Hasegawa, A., Nishimura, H., Matsuda, Y., Kunisato, Y., Morimoto, H., & Adachi, M. (2016). Is trait rumination associated with the ability to generate effective problem solving strategies? Utilizing two versions of the Means-Ends Problem-Solving Test. Journal of Rational-Emotive & Cognitive-Behavior Therapy, 34, 14-30. [Link](https://pubmed.ncbi.nlm.nih.gov/26900257/)
 
### 2015

- [18] Tsukue, R., Okamoto, Y., Yoshino, A., Kunisato, Y., Takagaki, K., Takebayashi, Y., Tanaka, K., Konuma, K., Tsukue, I., & Yamawaki, S. (2015) Do Individuals with Alcohol Dependence Show Higher Unfairness Sensitivity? The Relationship Between Impulsivity and Unfairness Sensitivity in Alcohol-Dependent Adults. Alcoholism, clinical and experimental research, 39(10), 2016-2021.  [Link](https://onlinelibrary.wiley.com/doi/abs/10.1111/acer.12832)
 
- [17] Nishiyama,Y., Okamoto, Y., Kunisato, Y., Okada, G., Yoshimura, S., Kanai, Y., Yamamura, T., Yoshino, A., Jinnin, R., Takagaki, K., Onoda, K., & Yamawaki, S. (2015) fMRI Study of Social Anxiety during Social Ostracism with and without Emotional Support. PLoS ONE 10(5): e0127426. [Link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127426)

### 2014
 
- [16] Machino, A., Kunisato, Y., Matsumoto, T., Yoshimura, S., Ueda, K., Yamawaki, Y., Okada, G., Okamoto, Y., & Yamawaki, S (2014) Possible involvement of rumination in gray matter abnormalities in persistent symptoms of major depression: an exploratory magnetic resonance imaging voxel-based morphometry study, Journal of Affective Disorders, 168, 229-235. [Link](https://www.sciencedirect.com/science/article/abs/pii/S0165032714003917?via%3Dihub)
 
- [15] Yoshino, A., Okamoto, Y., Kunisato, Y., Yoshimura, Y., Jinnin, R., Hayashi, Y., Kobayakawa, M., Doi, M., Oshita, K., Nakamura, R., Tanaka, K., Yamashita, H., Kawamoto, M., & Yamawaki, S. (2014). Distinctive spontaneous regional neural activity in patients with somatoform pain disorder: A resting-state fMRI preliminary study, Psychiatry Research: Neuroimaging, 221(3), 246-248. [Link](https://www.sciencedirect.com/science/article/abs/pii/S0925492713003417?via%3Dihub)
 
- [14] Toki, S., Okamoto, Y., Onoda, K., Matsumoto, T., Yoshimura, S., Kunisato, Y., Okada, G., Shishida, K., Kobayakawa, M., Fukumoto, T., Machino, A., Inagaki, M., Yamawaki, S. (2014). Hippocampal activation during associative encoding of word pairs and its relation to symptomatic improvement in depression: A functional and volumetric MRI study. Journal of Affective Disorder, 152, 462-467. [Link](https://www.sciencedirect.com/science/article/abs/pii/S0165032713005892?via%3Dihub)
 
### 2013

- [13] Yoshimura, S., Okamoto, Y., Onoda, K., Matsunaga, M., Okada, G., Kunisato, Y., Yoshino, A., Ueda, K., Suzuki, S., & Yamawaki, S. (2013). Cognitive behavioral therapy for depression changes medial prefrontal and ventral anterior cingulate cortex activity associated with self-referential processing. Social Cognitive and Affective Neuroscience, 9(4), 487-493.  [Link](https://academic.oup.com/scan/article/9/4/487/1629777)
 
- [12] Takagaki, K., Okajima, I., Kunisato, Y., Nakajima, S., Kanai, Y., Ishikawa, S., & Sakano, Y. (2013). Preliminary assessment of the behavioral activation model in Japanese undergraduate students. Psychological Reports, 112(1), 47-59.  [Link](https://journals.sagepub.com/doi/abs/10.2466/02.15.21.PR0.112.1.47-59)
 
- [11] Koseki, S., Noda., T., Yokoyama, S., Kunisato, Y., Ito, D., Suyama, H., Matsuda, T., Sugimura, Y., Ishihara, N., Shimizu, Y., Nakazawa, K., Yoshida, S., Arima, K., Suzuki,S. (2013). The relationship between positive and negative automatic thought and activity in the prefrontal and temporal cortices: A multi-channel near-infrared spectroscopy (NIRS) study, Journal of Affective Disorders, 151(1), 352-359. [Link](https://www.sciencedirect.com/science/article/pii/S0165032713004461)
 
### 2012

- [10] Kinoshita, A., Okamoto, Y., Okada, G., Demoto, Y., Kunisato, Y., Yoshimura, S., Onoda,K., Kamachi, M., Yamawaki, S. (2012) Sex differences in neural activation to ambiguous facial expression in happy and sad context, Perceptual and Motor Skills, 115(2), 349-359. [Link](https://journals.sagepub.com/doi/abs/10.2466/22.24.PMS.115.5.349-359)
 
- [9] Kunisato, Y., Okamoto, Y., Ueda, K., Onoda, K., Okada, G., Yoshimura, S., Suzuki, S., Samejima, K., Yamawaki, S. (2012) Effects of depression on reward based decision making and variability of action in probabilistic learning, Journal of Behavior Therapy and Experimental Psychiatry, 43, 1088-1094.  [Link](https://www.sciencedirect.com/science/article/abs/pii/S000579161200047X?via%3Dihub)
 
- [8] Yoshino, A., Okamoto, Y., Onoda, K., Shishida, K., Yoshimura, S., Kunisato, Y., Demoto, Y., Okada, G., Toki, S., Yamashita, H., Yamawaki, S. (2012) Sadness enhances the experience of pain and affects pain-evoked cortical activities: An MEG study, The Journal of Pain,13, 628-635.  [Link](Sadness enhances the experience of pain and affects pain-evoked cortical activities: An MEG study)
 
- [7] Demoto, Y., Okada, G., Okamoto, Y., Kunisato, Y., Aoyama, S., Onoda, K., Munakata, A., Nomura, M., Tanaka, S. C., Schweighofer, N., Doya, K., Yamawaki, S. (2012) Neural And Personality Correlates of Individual Differences Related to the Effects of Acute Tryptophan Depletion on Future Reward Evaluation, Neuropsychobiology, 65, 55-64.  [Link](https://www.karger.com/Article/Abstract/328990)
 
 
### 2011

- [6] Okada, G., Okamoto, Y., Kunisato, Y., Aoyama, S., Nishiyama, Y., Yoshimura, S., Onoda, K., Toki, S., Yamashita, H., & Yamawaki, S. (2011) The effect of negative and positive emotionality on associative memory: An fMRI study, PLoS ONE, 6(9),e24862.  [Link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0024862)
 
- [5] Onoda, K., Okamoto, Y., Kunisato, Y., Aoyama, S., Shishida, K., Okada, G., Tanaka, SC., Schweighofer, N., Yamaguchi, S., Doya, K., & Yamawaki, S. (2011) Inter-individual discount factor differences in reward prediction are topographically associated with caudate activation, Experimental Brain Research, 212(4), 593-601.  [Link](https://link.springer.com/article/10.1007/s00221-011-2771-3)
 
- [4] Kunisato, Y., Okamoto, Y., Okada, G., Aoyama, S., Nishiyama, Y., Onoda, K., Yamawaki, S. (2011)Personality traits and the amplitude of spontaneous low-frequency oscillations during resting state, Neuroscience Letters, 492(2), 109-113.  [Link](https://www.sciencedirect.com/science/article/abs/pii/S0304394011001133)
 
- [3] Kunisato,Y., Okamoto, Y., Okada, G., Aoyama, S., Demoto, Y., Munakata, A., Nomura, M., Onoda, K., Yamawaki, S. (2011) Modulation of default - mode network activity by acute tryptophan depletion is associated with mood change：A resting state functional magnetic resonance imaging study. Neuroscience Research, 69, 129-134. [Link](https://www.sciencedirect.com/science/article/pii/S016801021002835X?via%3Dihub)

### 2010

- [2] Matsunaga, M., Okamoto, Y., Suzuki, S., Kinoshita, A., Yoshimura, S., Yoshino, A., Kunisato, Y. & Yamawaki, S. (2010). Psychosocial functioning in patients with treatment-resistant depression after group cognitive behavioral therapy. Bmc Psychiatry, 10(1), 22. [Link](https://bmcpsychiatry.biomedcentral.com/articles/10.1186/1471-244X-10-22)
 
- [1] Yoshino, A., Okamoto, Y., Onoda, K., Yoshimura, S., Kunisato, Y., Demoto, Y., Okada, G, & Shigeto, Y. (2010). Sadness enhances the experience of pain via neural activation in the anterior cingulate cortex and amygdala: An fMRI study. Neuroimage, 50(3), 1194-1201. [Link](https://www.sciencedirect.com/science/article/abs/pii/S1053811909012658)