---
title: "学術論文（日本語）"
---

### 印刷中

- [43]  国里愛彦・山本哲也　マインドフルネス研究の未来を切り開く新たな方法論　心理学評論

- [42] 国里愛彦・土屋政雄　認知行動療法における研究の再現可能性を高める　認知行動療法研究

- [41] 国里愛彦・片平健太郎・沖村 宰・山下祐一　認知行動療法に対する計算論的アプローチ　認知行動療法研究　[Link](https://www.jstage.jst.go.jp/article/jjbct/advpub/0/advpub_20-036/_article/-char/ja/)

### 2021

- [40] 国里愛彦(2021)恐怖の再発と潜在原因モデルー計算論的精神医学入門ー　基礎心理学研究, 40(1), 50-53.[Link](https://www.jstage.jst.go.jp/article/psychono/40/1/40_40.11/_pdf/-char/ja)

- [39] 国里愛彦・遠山朝子(2021)心身医学研究とオープンサイエンス　心身医学研究, 61, 689-693.[Link](https://www.jstage.jst.go.jp/article/jjpm/61/8/61_61.8_689/_article/-char/ja/)

### 2020

- [38] 下野有紀・長谷川晃・土原浩平・国里愛彦 (2020).大学生用ひきこもり親和性尺度の作成 感情心理学研究, 27(2), 51-60. [Link](https://ci.nii.ac.jp/naid/130007823133)

### 2019

- [37] 畑琴音・小野はるか・小川祐子・竹下若那・国里愛彦・鈴木伸一 (2019).がん患者用活動抑制尺度(SIP-C)の作成と信頼性・妥当性の検討　総合病院精神医学, 31(4), 422-429. [Link](https://jglobal.jst.go.jp/detail?JGLOBAL_ID=202002290198644052)

- [36] 杣取恵太・国里愛彦 (2019). アンヘドニア(anhedonia)と遅延割引：Lempert & Pizzagalli(2010)の追試　心理学評論, 62(3), 231-243. [論文PDF](materials/PDF/somatori_kunisato_2019_replication_study.pdf),　[採択後プレプリント](https://psyarxiv.com/4zbc5/)，　[事前審査のプレプリントとマテリアル](https://osf.io/vj7w3/)，　[データと解析コード](https://github.com/ykunisato/somatori_kunisato_2019_replication_study)，　[特集号のページ](http://team1mile.com/sjpr62-3/)

- [35] 国里愛彦・片平健太郎・沖村 宰・山下祐一 (2019).うつに対する計算論的アプローチ：強化学習モデルの観点から　心理学評論, 62(1), 88-103. [PDF](materials/PDF/うつに対する計算論的アプローチ 強化学習モデルの観点から.pdf) [Link](https://ci.nii.ac.jp/naid/130007749836)

- [34] 佐藤秀樹・国里愛彦・小関俊祐・鈴木伸一 (2019). Rumination about an Interpersonal Offense Scale（RIO）日本語版の作成と信頼性・妥当性の検討　認知療法研究，12(2)，111-119． [Link](https://ci.nii.ac.jp/naid/40022008784)

- [33] 沖村 宰・片平健太郎・国里愛彦・山下祐一(2019).　統合失調症のコンピュータシミュレーション　BRAIN and NERVE, 71(7), 771-783. [Link](https://ci.nii.ac.jp/naid/40021968927)

- [32] 伊藤理紗・矢島　涼・佐藤秀樹・樋上巧洋・松元智美・並木伸賢・国里愛彦・鈴木伸一 (2019). 恐怖の高まりを伴う安全確保行動がエクスポージャーの治療効果に与える影響　認知行動療法研究, 45(1)，13-22．[Link](https://ci.nii.ac.jp/naid/130007661439)

- [31] 杣取恵太・下斗米淳・国里愛彦(2019).　メタ認知における２側面 -絶対的感度と相対的感度-　行動科学, 58(1), 27-38. [Link](http://www.jabs.jp/kikanshi_backnum.html#58-1)

### 2018

- [[30] 国里愛彦 (2018) 臨床心理学と認知モデリング　心理学評論, 61(1), 55-66.](materials/papers/Kunisato_2018_Clinical_psychology_and_cognitive_modeling.pdf) [Link](https://ci.nii.ac.jp/naid/130007678116)

- [29] 国里愛彦 (2018) 計算論的臨床心理学からみた認知行動療法　認知療法研究, 11(1), 2-12. [Link](https://ci.nii.ac.jp/naid/40021622191)

- [28] 畑 琴音・小川祐子・小野はるか・竹下若那・佐藤秀樹・国里愛彦・鈴木伸一 (2018) がん患者に対する行動活性化療法の構成要素に関する文献レビュー　認知療法研究, 11(1), 42-51. [Link](https://ci.nii.ac.jp/naid/40021622253)

- [27] 小関俊祐・小関真実・中村元美・大谷哲弘・国里愛彦 (2018) 日本語版児童用Behavioral Inhibition System and Behavioral Activation System Scale(児童用BIS/BAS尺度)の作成と信頼性・妥当性の検討　認知行動療法研究, 44(1), 29-39. [Link](https://ci.nii.ac.jp/naid/130007397685)

### 2016

- [26] 伊藤理紗・兼子唯・巣山晴菜・佐藤秀樹・横山仁史・国里愛彦・鈴木伸一 (2016) 単一恐怖症状の高い大学生における，エクスポージャー中の安全確保行動の効果　行動療法研究, 42(2), 237 -246. [Link](https://ci.nii.ac.jp/naid/130007638906)
 
### 2015

- [25] 小川祐子・武井優子・古賀晴美・島田真衣・長尾愛美・佐々木美保・国里愛彦・谷川啓司・鈴木伸一(2015) 補完代替療法をうける外来がん患者を対象とした主治医と話すことへのためらいの構成概念の検討　心身医学 55(7), 873-883. [Link](https://www.jstage.jst.go.jp/article/jjpm/55/7/55_KJ00009985734/_article/-char/ja/)
 
- [24] 国里愛彦 (2015) 系統的展望とメタアナリシスの必須事項　行動療法研究, 41(1), 3-12. [Link](https://www.jstage.jst.go.jp/article/jjbt/41/1/41_KJ00009813711/_article/-char/ja/)
 
### 2014
 
- [23] 岡田剛・岡本泰昌・志々田一宏・上田一貴・小野田慶一・国里愛彦・田中沙織・銅谷賢治・山脇成人 (2014) うつ病の脳内メカニズム:Functional MRIを用いた検討　精神神経学雑誌 116(10), 825-831. [Link](https://ci.nii.ac.jp/naid/40020244166)
 
- [22] 国里愛彦・岡本泰昌・吉村晋平・松永美希・岡田剛・吉野敦雄・小野田慶一・上田一貴・鈴木伸一・山脇成人（2014）うつ病の認知行動療法の脳内作用メカニズムと今後の展開　Depression Frontier, 12(2), 41-45. [Link](https://ci.nii.ac.jp/naid/40020289988)
 
- [21] 巣山晴菜 ・兼子唯・伊藤理紗・横山仁史・伊藤大輔・国里 愛彦・貝谷久宣・鈴木伸一(2014)重症社交不安障害患者における拒絶に対する過敏性と うつ症状が社交不安症状に与える影響性の検討　不安障害研究, 6(1), 7-16. [Link](https://ci.nii.ac.jp/naid/130004700826)
 
- [20] 国里愛彦・岡本泰昌・吉村晋平・松永美希・岡田剛・吉野敦雄・小野田慶一・上田一貴・鈴木伸一・山脇成人（2014）うつ病における認知行動療法の神経作用メカニズム　ストレス科学, 29(1), 45-54. [Link](https://ci.nii.ac.jp/naid/40020309737)
 
### 2013
 
- [19] 髙垣耕企・岡島　義・国里愛彦・中島　俊・金井嘉宏・石川信一・坂野雄二 （2013）Behavioral Activation for Depression Scale (BADS) 日本語版の作成　精神科診断学, 6(1)，76- 85.
 
- [18] 桂川泰典・国里愛彦・菅野純・佐々木和義（2013）日本語版セッション評価尺度（The Japanese Session Evaluation Questionnaire:J-SEQ)作成の試み―カウンセラー評定による検討ー　パーソナリティ研究, 22(1), 73-76. [Link](https://ci.nii.ac.jp/naid/130003363154)
 
- [17] 国里愛彦（2013）うつとストレスに対する計算論的アプローチ: 計算論的精神医学入門　ストレス科学, 28(2), 101-107. [Link](https://ci.nii.ac.jp/naid/40020309870)
 
### 2012
 
- [16] 松永美希・鈴木伸一・岡本泰昌・吉村晋平・国里愛彦・神人　蘭・吉野敦雄・西山佳子・山脇成人(2012)　心理士が中心に実施したうつ病の集団認知行動療法-大学病院における取り組みから-　行動療法研究, 38 (3), 181-191. [Link](https://www.jstage.jst.go.jp/article/jjbt/38/3/38_KJ00008598587/_article/-char/ja)
 
- [15] 佐々木美保・武井優子・小川佑子・島田真衣・長尾愛美・国里愛彦・鈴木伸一（2012）　生活習慣病への認知行動療法　認知療法研究, 5(2), 128-136. [Link](https://ci.nii.ac.jp/naid/40019863650)
 
- [13] 吉野敦雄・岡本泰昌・小野田慶一・吉村晋平・国里愛彦・岡田剛・高橋輝道・山脇成人 (2012) 悲しみによる主観的な痛みの増強と脳機能の変化　PAIN RESEARCH, 27(1): 7 -15. [Link](https://ci.nii.ac.jp/naid/130004651927)

### 2011
 
- [12] 岡島　義・国里愛彦・中島　俊・髙垣耕企（2011）　うつ病に対する行動活性化療法―歴史的展望とメタ分析―　心理学評論, 54(4), 473-488. [Link](https://ci.nii.ac.jp/naid/130007436867)
 
- [11] 髙垣耕企・岡島　義・国里愛彦・中島　俊・秋田久美・金井嘉宏・石川信一・坂野雄二 （2011）　Cognitive-Behavioral Avoidance Scale (CBAS) 日本語版の作成　精神科診断学, 4(1), 104-113. [Link](https://jglobal.jst.go.jp/detail?JGLOBAL_ID=201602203837155636)
 
- [10] 国里愛彦・髙垣耕企・岡島義・中島俊・石川信一・金井嘉宏・岡本泰昌・坂野雄二・山脇成人　(2011)　日本語版Environmental Reward Observation Scale (EROS)の作成と信頼性・妥当性の検討　行動療法研究, 37(1), 21-31. [Link](https://www.jstage.jst.go.jp/article/jjbt/37/1/37_KJ00008938280/_article/-char/ja)
 
### 2010

- [9] 岡本泰昌・岡田剛・吉村晋平・国里愛彦・西山佳子・土岐茂・小野田慶一・山脇成人 (2010) うつ病の認知に関わる神経生理学的基盤　認知神経科学, 12(3), 140-148. [Link](https://ci.nii.ac.jp/naid/130004552235)
 
- [8] 伊藤大輔・国里愛彦・浅本有美・鈴木伸一(2010). 高校新入生のストレッサーとコーピングがストレス反応に及ぼす影響-4ヵ月フォローアップによる継時的検討- ス トレス科学, 24(4), 261-270. [Link](https://ci.nii.ac.jp/naid/40017196456)
 
- [7] 国里愛彦・伊藤大輔・浅本有美・長原啓三・鈴木伸一 (2010).　高校新入生ストレッサー尺度の作成と信頼性・妥当性の検討　ストレス科学, 24(4), 271-280. [Link](https://ci.nii.ac.jp/naid/40017196457)
 
- [6] 浅本有美・国里愛彦・村岡洋子・在原理沙・堂谷智香子・田所健児・伊藤大輔・伊藤有里・佐々木美保・尾形明子・ 鈴木伸一 (2010).　小学校1年生に対する集団社会的スキル訓練の試み : 取り組みやすく, 動機づけを高める集団SSTプログラム　行動療法研究, 36(1), 57-68. [Link](https://www.jstage.jst.go.jp/article/jjbt/36/1/36_KJ00009018587/_article/-char/ja)

### 2009
 
- [5] 岡本泰昌・小野田慶一・吉村晋平・吉野敦雄・国里愛彦・出本吉彦・岡田剛・山下英尚・山脇成人 (2009).　ストレス適応破綻の神経生理学的基盤　皮膚の科学, 8, 603-609. [Link](https://ci.nii.ac.jp/naid/130004934566)
 
- [5] 小野田慶一・岡本泰昌・国里愛彦・岡田剛・山脇成人 (2009). 遅延報酬選択における衝動性と抑うつ傾向　脳と精神の医学, 20(3), 249-254. [Link](https://ci.nii.ac.jp/naid/10028262508)
 
- [4] 小野田慶一・岡本泰昌・国里愛彦・岡田剛・山脇成人 (2009). 将来予期の神経メカニズムとうつ病に関する脳機能画像研究　神経内科,71(2), 105-111. [Link](https://www.molcom.jp/products/detail/46024/)
 
- [3] 国里愛彦・岡田 剛・岡本泰昌(2009). 線条体の強化学習機能 BRAIN & NERVE,61(4),405-411. [Link](https://ci.nii.ac.jp/naid/40016613392)

### 2008
 
- [2] 小野田慶一・岡本泰昌・国里愛彦・山脇成人 (2008). 情動予期の神経基盤に関するfMRI研究 生理心理学と精神生理学,26(3),229-235. [Link](https://ci.nii.ac.jp/naid/130004715505)
 
- [1] 国里愛彦・山口陽弘・鈴木伸一(2008). Cloningerの気質・性格モデルとBig Fiveモデルとの関連性　パーソナリティ研究,16,324-334. [Link](https://ci.nii.ac.jp/naid/110006820559)