---
title: "書籍"
---
### 2025

- [36] 国里愛彦(2025). 心理構成主義的感情理論から見た心理療法―認知行動療法の立場から『感情がつくられるものだとしたら　世界はどうなるのか
－バレットの構成主義的情動理論をめぐる、さまざまな領域からの考察－』金芳堂, pp.214-224.

- [35] 宗田卓史・遠山朝子・国里愛彦・沖村宰・片平健太郎・山下祐一(2025).『R/Pythonではじめる計算論的精神医学』 金芳堂 [Amazon.co.jp](https://www.amazon.co.jp/gp/product/4765320448/ref=ox_sc_saved_image_8?smid=AN1VRQENFRJN5&psc=1)

- [34] 国里愛彦(2025).　「第２章　行動科学と神経科学による基礎理論」　M・G・クラスク, H・J・ドゥール, M・トレナー, A・E・ミューレ (著)『不安とうつへのポジティブ感情トリートメント【セラピストガイド】』鈴木伸一・伊藤正哉 (監訳)　北大路書房

- [33] 国里愛彦(2025). 「第１章　ポジティブになれない」Ａ．Ｅ．ミューレ, Ｈ．Ｊ．ドゥール, Ａ．Ｇ．Ｌ．ギニアード, Ｍ．Ｇ．クラスク (著)　『不安とうつへのポジティブ感情トリートメント【ワークブック】』
鈴木伸一・伊藤正哉 (監訳)　北大路書房



### 2024

- [32] 国里愛彦(2024). 「第11章　ネットワークにおける変化のモデリング(pp.305-330)」・「第13章　心理ダイナミクスについての理想化されたモデリング(pp.365-3385)」アデラ＝マリア・イスヴォラヌ，サシャ・エプスカンプ，ローレンス・J・ウォルドープ，デニー・ボースブーム（編）『心理ネットワークアプローチ入門：行動科学者と社会科学者のためのガイド』
樫原潤・小杉考司（監訳）　勁草書房


### 2023

- [31] 国里愛彦(2023). 「第11章　治療がたどる道のり」ホフマン, S.G., ヘイズ, S.C., & ロールシャイト, D.N(著)『プロセス・ベースド・セラピーをまなぶ』菅原大地・樫原潤・伊藤正哉（監訳）金剛出版, pp.199-218.

- [30] 国里愛彦(2023). 「EysenckのパーソナリティモデルとBig Five(pp.140-141)」・「BIS/BASとBig Five(pp.142-143)」谷伊織・阿部晋吾・小塩真司 (編)　『Big Fiveパーソナリティ・ハンドブック　5つの因子から「性格」を読み解く』福村出版. 2023年6月9日

### 2022

- [29] 国里愛彦(2022). 「第５章　神経科学研究」　岩壁茂・杉浦義典（編）『現代の臨床心理学４　臨床心理学研究法』　東京大学出版会，pp.195-210. 2022年9月16日

- [28] 国里愛彦(2022).「第5章　気質とパーソナリティ」Chen, X & Schmidt, L.A.(著)『児童心理学・発達科学ハンドブック【第3巻】』 リチャード・M・ラーナー(編集主幹),マイケル・E・ラム(編)，二宮克美・子安増生(監訳), 小塩真司・仲真紀子(編訳), 福村出版,pp.220-286.[link](https://www.fukumura.co.jp/book/b612546.html)


### 2021

- [27] 国里愛彦(2021). 心理職のための神経科学入門　公認心理師のための「心理査定」講義　北大路書房　2021年4月20日

- [26] 国里愛彦(2021). 「STROBE声明」,「STARD声明」，「CARE声明」，「CONSORT声明」，「場面見本法」，「PRISMA声明」，「PECO／PICO」，「無作為化比較試験」，「臨床試験」　『有斐閣　現代心理学辞典』有斐閣 2021年2月25日


### 2020

- [25] 国里愛彦(2020). 第１章「動機づけ」　『公認心理師の基礎と実践9:感情・人格心理学』pp.31-41(全197ページ). 遠見書房 

### 2019

- [24]宗田卓史・国里愛彦・片平健太郎・沖村 宰・山下祐一(2019).　計算神経科学と精神医学：情報の観点から精神疾患を見る　『Power Mook 精神医学の基盤』 Vol 4 No1, pp107-117.  学樹書院

- [23]「診断ガイドライン(杣取恵太・国里愛彦，pp.632-633)」，「アウトカムの重要性(杣取恵太・国里愛彦，pp.658-659)」，「有害事象(国里愛彦，pp.660-661)」，「再現可能性(国里愛彦，pp.674-675)」『認知行動療法事典』丸善出版 2019年9月3日　[Amazon.co.jp](https://www.amazon.co.jp/dp/4621303821/ref=cm_sw_r_tw_dp_U_x_ySkBDbK4HP0P8)

- [22] 国里愛彦・片平健太郎・沖村 宰・山下祐一(2019). 『計算論的精神医学: 情報処理過程から読み解く精神障害』  勁草書房 2019年1月25日 [Amazon.co.jp](https://www.amazon.co.jp/dp/432625131X/ref=cm_sw_r_tw_dp_U_x_KM7SCbP877MA8)

- [21] 国里愛彦(2019). 第３章 「レスポンデント学習の理論モデル(pp.275-279)」，「レスポンデント学習の理論に基づくケースフォーミュレーション(pp.280-284)」下山晴彦・伊藤絵美・黒田美保・鈴木伸一・松田　修（編)『公認心理師技法ガイド：臨床の場で役立つ実践のすべて』文光堂 2019年3月26日　 [Amazon.co.jp](https://www.amazon.co.jp/dp/4830636262/ref=cm_sw_em_r_mt_dp_U_DL7SCbXZFBA0R)



### 2018

- [20] 国里愛彦(2018). 「第14章　アセスメントにおける倫理的問題と法的問題」スーザン C. ウィストン(著)石川信一・佐藤寛・高橋史（監訳）『カウンセリングにおけるアセスメントの原理と適用』，金子書房，pp.343-364. [Amazon.co.jp](http://amzn.asia/d/7dg5Zgq)

- [19] 国里愛彦(2018). 「第14章　いつになったら原稿を書くのか？: 執筆量モニタリングにおける変化点検出」『たのしいベイズモデリング 事例で拓く研究のフロンティア』豊田秀樹(編), 北大路書房, pp.149-159. [Amazon.co.jp](http://amzn.asia/d/2r9QFKj)

- [18] 国里愛彦(2018). 「第3章7節　脳神経系の神経心理学的理解と認知機能の障害」　『公認心理師養成のための保健・医療系実習ガイドブック』鈴木伸一・田中恒彦・小林清香（編）,　北大路書房, pp.79-86. [Amazon.co.jp](http://amzn.asia/d/9TMdHZs)

- [17] 国里愛彦(2018). 「第5章　健康関連のパーソナリティの測定と評価」　『健康心理学の測定法・アセスメント』鈴木伸一（編）, ナカニシヤ出版, pp.66-82. [Amazon.co.jp](http://amzn.asia/d/73OpXuw)


### 2017

- [16] 国里愛彦(2017).「第24章　被予測変数がカウント変数の場合」』『ベイズ統計モデリング: R,JAGS, Stanによるチュートリアル 原著第2版』John K. Kruschke著，前田和寛・小杉考司監訳, 共立出版, pp.711-727.[Amazon.co.jp](http://amzn.asia/i6FoTrJ)

- [15] 国里愛彦(2017). 「Chapter 2 心の源としての感覚・知覚・認知」・「Chapter 3 心の表れとしての行動」　『対人援助と心のケアに活かす心理学』鈴木伸一(編) , 有斐閣, pp.9-33. [Amazon.co.jp](http://amzn.asia/hZ4yMKn)

- [14] 国里愛彦(2017). 「第５章　臨床心理学研究におけるサンプルサイズ設計」　『心理学のためのサンプルサイズ設計入門』　村井潤一郎・橋本貴充（共編）,　講談社，pp.86-106. [Amazon.co.jp](http://amzn.asia/0GOsHDM)

### 2016

- [13] 国里愛彦 (2016). 脳画像検査　『公認心理師必携　精神医療・臨床心理の知識と技法』下山晴彦・中嶋義文(編)　医学書院　pp197-198. 2016/9/1 [Amazon.co.jp](http://amzn.asia/cWb3VuR)
 
- [12] 国里愛彦 (2016). 「2.4 不適応の問題」&「2.5 心理的援助（心理的介入）」　『図説　現代心理学入門 [四訂版]』金城辰夫監修、山上精次・藤岡新治・下斗米淳(共編)　培風館 pp.56-65. 2016/3/30 [Amazon.co.jp](http://amzn.asia/3mCXXJN)
 
### 2015

- [11] 国里愛彦(2015) 行動医学と生物統計学 p73-78「行動医学テキスト」日本行動医学会編集（編集委員：野村忍・堤明純・島津明人・中尾睦宏・吉内一浩）2015/10/25  [Amazon.co.jp](http://amzn.asia/cpANGJ5)
 
### 2013

- [10] 『セラピストのための行動活性化ガイドブック＜うつ病を治療する10の中核原則＞』坂井誠・大野裕（監訳）創元社，2012年（担当した章：１章「序論　行動活性化の歴史」)  [Amazon.co.jp](http://amzn.asia/9yjCNHr)
 
- [9] 『パーソナリティ心理学ハンドブック』　二宮克美・浮谷秀一・堀毛一也・安藤寿康・藤田主一・小塩真司・渡邊芳之（編）　福村出版　2013年（国里愛彦（著）「脳神経科学とパーソナリティ」, p85-91） [Amazon.co.jp](http://amzn.asia/cKObuiz)
 
- [8] 『Encyclopedia of Behavioral Medicine』 「Type A」Kunisato Y．& Suzuki，S. Springer, 2013.  [Amazon.co.jp](http://amzn.asia/6FVAVlc)

- [7] 『APA心理学大辞典』　Gary R. VandenBos (監修), 繁桝算男・四本裕子(監訳)　培風館, 2013年（一部翻訳）.[Amazon.co.jp](http://amzn.asia/eRIahSG)
 
### 2012

- [6] 『うつを克服するための行動活性化練習帳：認知行動療法の新しい技法』大野裕・岡本泰昌（監訳）うつの行動活性化療法研究会（訳）　創元社，2012年（担当した章：１章)  [Amazon.co.jp](http://amzn.asia/9GW1z8K)
 
### 2011

- [5] 『さあ！やってみよう　集団認知行動療法　うつ・不安への支援のために』集団認知行動療法研究会（監修） 医学映像教育センター　2011年　（松永美希・岡本泰昌・鈴木伸一・吉村晋平・国里愛彦・山脇成人(著) 「第２章 各施設の実践例: 広島大学病院精神神経科の場合」, p 20-30)  [Amazon.co.jp](http://amzn.asia/cyzswp7)
 
- [4] 『うつ病の行動活性化療法：新世代の認知行動療法によるブレイクスルー』　熊野宏昭・鈴木伸一（監訳）日本評論社, 2011年 (担当した章：2章，6章，7章，8章，9章，10章，付録）  [Amazon.co.jp](http://amzn.asia/5Wp6dvL)
 
- [3] 『うつ病の集団認知行動療法実践マニュアル：再発予防や復職支援に向けて』松永美希・吉村晋平・国里愛彦・鈴木伸一 (著) 鈴木伸一・岡本泰昌・松永美希（編）日本評論社　2011年  [Amazon.co.jp](http://amzn.asia/4jBendY)
 
- [2] 『うつ病治療ハンドブック　診療のコツ』　大野裕（編）　金剛出版　2011年（国里愛彦・岡本泰昌（著）「行動活性化療法」, p 264-270）  [Amazon.co.jp](http://amzn.asia/72OLvVf)
 
### 2008

- [1] 『さあ！はじめよう　うつ病の集団認知行動療法』　秋山剛・大野裕（監修）医学映像教育センター 2008年 (松永美希・鈴木伸一・岡本泰昌・木下亜紀子・上田一貴・小野田慶一・吉野敦雄・国里愛彦・山脇成人 (著) 「広島大学病院精神科における集団認知行動療法」, p146-149)  [Amazon.co.jp](http://amzn.asia/dn1cUT7)