---
title: "紀要論文・報告書・研究論文以外の原稿など"
---

### 2020

- [20] 国里愛彦　(2020). あなたの解析，再現できますか？統計解析の再現可能性を高めるために 週刊医学界新聞 第3357号　2020年2月3日 [リンク](http://www.igaku-shoin.co.jp/paperDetail.do?id=PA03357_03)

- [19] 国里愛彦　(2020). 自著を語る「計算論的精神医学: 情報処理過程から読み解く精神障害」　心理学ワールド 88号　[リンク](https://psych.or.jp/publication/world088/pw18)


- [18] 国里愛彦　(2020). 再現可能な心理学研究入門 専修大学人間科学論集心理学篇　[プレプリント](https://psyarxiv.com/x8js5/)

### 2018

- [17] 杣取恵太・国里愛彦　(2018).情動喚起刺激を用いた恐怖条件づけパラダイムの動向　専修人間科学論集　心理学篇, 8(1), 7-13.

- [16] 土原浩平・工藤志野・二瓶正登・国里愛彦　(2018).共感性および連合学習理論の観点からみたマインドフルネスについての文献研究　専修人間科学論集　心理学篇, 8(1), 15-22.

- [15] 竹下若那・小川祐子・小野はるか・畑琴音・佐藤秀樹・伊藤理紗・市倉加奈子・松永美希・国里愛彦・鈴木伸一(2018).　非致死性トラウマ体験のある大学生におけるストレスコーピングと主観的幸福感の関連　早稲田大学臨床心理学研究，17，43-50．

### 2016

- [14] 杣取恵太・坂本次郎・時田椋子・鈴木彩夏・国里愛彦 (2016). 診断精度研究の系統的レビューとメタアナリシス  専修人間科学論集　心理学篇, 6(1), 41-58. [論文へのリンク](http://ir.acc.senshu-u.ac.jp/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=9918&item_no=1&page_id=13&block_id=52)

- [13] 国里愛彦・坂本次郎・杣取恵太(2016). 複雑な臨床的問題を階層ベイズで解く 専修大学社会知性開発研究センター/心理科学研究センター年報, 5, 46-53.  [論文へのリンク](http://ir.acc.senshu-u.ac.jp/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=9863&item_no=1&page_id=13&block_id=52)

### 2014

- [12] 国里愛彦 (2014). うつ病に対する認知行動療法の神経作用機序 専修大学社会知性開発研究センター/心理科学研究センター年報, 2, 127–145.  [論文へのリンク](http://ir.acc.senshu-u.ac.jp/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=6942&item_no=1&page_id=13&block_id=52)

- [11] 大月　友・国里愛彦・澤　幸祐・関口正幸・杉浦義典 (2014) 不安に関する基礎理論の最前線と臨床への還元 7(2), 134-143.

### 2013

- [10] 国里愛彦 (2013). うつ病と意志決定：計算論的臨床心理学からみたうつ病 専修大学社会知性開発研究センター/心理科学研究センター年報, 2, 127–145.  [論文へのリンク](http://ir.acc.senshu-u.ac.jp/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=5002&item_no=1&page_id=13&block_id=52)

- [9] 国里愛彦（2013）共同研究の方法　臨床心理学, 13(3), 384-385.

- [8] 国里愛彦・鈴木伸一（2013）マインドフルネス/行動活性化療法/弁証法的行動療法　精神科臨床サービス,13:212-213.

### 2008

- [7] 髙村真広・国里愛彦・徳永智子・蔵永　瞳・深瀬裕子・宮谷真人　(2008). Rによる一要因分散分析と多重比較, 広島大学心理学研究, 8, 177-190.  [論文へのリンク](http://ir.lib.hiroshima-u.ac.jp/ja/00026799)
 
- [6] 徳永智子・国里愛彦・蔵永 瞳・髙村真広・深瀬裕子・宮谷真人　(2008). Rで始める心理統計, 広島大学心理学研究, 8, 163-176.  [論文へのリンク](http://ir.lib.hiroshima-u.ac.jp/ja/list/HU_journals/AA11616129/--/8/item/26798)
 
- [5] 国里愛彦・山口陽弘・鈴木伸一(2008). Grayの気質理論と反応スタイル理論との関連　群馬大学教育実践研究,25,281-289.
 
- [4] 国里愛彦・山口陽弘・鈴木伸一(2008). うつ病において報酬系の機能は阻害されるか？-うつ病と報酬系に関する認知神経科学的検討-　群馬大学教育学部紀要　人文・社会科学編,57,219-234.  [論文へのリンク](https://gair.media.gunma-u.ac.jp/dspace/handle/10087/3013)

- [3] 髙田未里・ 島 悟・北條稔・ 鈴木綾子・小幡真希・土肥公子・福岡トシエ・太田真由美・宮良幹子・弓掛つね子・衛藤由美・寺岡貴子・国里愛彦・大塚泰正・馬ノ段梨乃・富永知美・赤畠鮎 美　(2008).　大都市圏における中小零細事業場を対象とした自殺予防対策に関する調査研究　島　悟（代表）　労働者の自殺予防に関する介入研究　厚 生労働科学研究費補助金（労働安全衛生総合研究事業）平成19年度分担研究報告書　厚生労働省，p.28-60.

### 2007

- [2] 国里愛彦・山口陽弘・大久保智沙・鈴木伸一(2007). Temperament and Character Inventoryの因子的妥当性について　群馬大学教育実践研究,24,387-396.
 
- [1] 国里愛彦・山口陽弘・鈴木伸一(2007).　パーソナリティ研究と神経科学をつなぐ気質研究について　群馬大学教育学部紀要　人文・社会科学編,56,359-377.  [論文へのリンク](https://gair.media.gunma-u.ac.jp/dspace/handle/10087/1452)
 