---
title: "Code & Tips"
---

☆は，学部ゼミでの必修事項,○は推奨事項です。

## ゼミで使うツール

- Slack: ゼミ内での連絡で使います(スマホとPCにアプリを入れておきましょう)。
- RStudio Server: データ収集（調査票，実験課題の作成），データ解析，卒論・修論の執筆のために使います。
- GitHub: 卒論・修論に関連した各種ファイルを指導教員と共有したり，バージョン管理するために使います。
- OSF:事前登録で使います。整理された研究内容のアップロードにも使います。
- Googleスライド：ゼミでの口頭発表の際に使います。
- Googleドキュメント：ゼミでのディスカッションのメモなどに使います。
- Meet: 大学が契約しているGoogleクラスルームのMeetです。対面でも画面共有で使います。
- JupyterHub: PythonやJuliaを用いたデータ解析のために使います(PythonとJuliaを使う学生のみアカウントを発行します)。
- JATOS: jsPsychで作成した認知課題・質問紙でデータ収集するために使います（JATOSでデータ収集する学生にのみアカウントを発行します）。

＊国里のゼミではパソコンが必須になります。コロナ対策のためパソコンのあるゼミ室ではなく，広い教室を使うので各自ノートパソコンを持ってくるようにしてください。ノートパソコンがない・持ってこれない場合は，国里の方で毎回貸し出し可能ですので，申し出てください。

<br />

## ゼミの準備

- [GitHubの準備](how-to-github.html) ☆

- [OSFの準備](how-to-osf.html) ☆

- [RStudioで研究を行う準備](how-to-write-with-rstudio.html)　☆

- [研究室での日々のルーティン作業](how-to-labnote.html) ☆

<br />

## 認知課題と質問紙の作成

- [jsPsychを用いた認知課題の作成1: jsPsychとJavaScript入門](how-to-jspsych1.html)　☆

- [jsPsychを用いた認知課題の作成2: ストループ課題](how-to-jspsych2.html)　☆

- [jsPsychを用いた認知課題の作成3: 逆転学習課題](how-to-jspsych3.html)　☆

- [jsPsychを用いた認知課題の作成4: 音声や動画の呈示と同意画面について](how-to-jspsych4.html)　☆

- [jsPsychを用いた質問票の作成](how-to-jspsych5.html)　☆

<br />

### jsPsych以外の方法

- [PsychoPyを用いた認知課題の作成](https://github.com/ykunisato/training-of-psychopy)

- [Presentationを用いた認知課題の作成](how-to-presentation.html)

<br />

## JATOSを用いた実験実施方法

- [JATOSをDockerを使ってローカルPCに導入する方法](how-to-jatos-local.html)　○

- [JATOSをDockerを使ってサーバーに導入する方法](how-to-jatos-web.html)　○

- [JATOSをローカルで使用する方法](how-to-jspsych-jatos-local.html)　○

- [JATOSをサーバーで使用する方法](how-to-jspsych-jatos-web.html)　○

- [jsPsychとlab.jsをまぜてJATOSで動かす方法](how-to-labjs-jspsych-jatos.html) 

- [Data URIによってJATOSサーバーの負荷を低くする方法](jspsych-data-uri.html)　

- [JATOSでコンポーネント間でIDなどの対応づけをする方法](jspsych-id-jatos.html)

- [JATOSでローカルにもバックアップをとる方法](japsych-jatos-locak-backup.html)

<br />

### JATOS以外の方法

- [jsPsychを用いたWEB実験(Firebaseを使う方法)](how-to-jspsych-firebase.html)

- [jsPsychを用いたWEB実験(Pavloviaを使う方法)](how-to-jspsych-pavlovia.html)

- [jsPsychを用いたWEB実験(Google Spreadsheetを使う方法)](how-to-jspsych-google-sheet.html)

<br />

## データ解析

- [R言語の基本](how-to-R-language.html) ☆

- [認知課題の解析データセット作成](how-to-dataHandling.html)　☆

- [オープンデータの利用法](how-to-open-data.html)

- [オープンデータの作り方](https://ykunisato.github.io/ccp-lab-slide/open_data/open_data.html)

- [事前登録をしてみよう！](how-to-preregistration-aspredicted.html)

- [再生可能なデータ解析入門](how-to-reproducible-analysis.html)　

- [Docker-composeを使ってGCE上のRstudio serverをHTTPS化する方法](how-to-rstudio-gce-https.html)

- [Docker-composeを使ってGCE上の複数のサービス(Rstudio, Jupyter notebook, JATOS, elabFTW)をHTTPS化する方法](how-to-docker-compose-https.html)

- [２次分析研究](https://ykunisato.github.io/ccp-lab-slide/spring_seminar_JSSP_2021/secondary_analysis/slide.html#1)

- [今日からできる再現可能な論文執筆(JPA2020・TWS)](https://ykunisato.github.io/jpa2020-tws-002/)


<br />

## 認知モデリング
### 強化学習モデル
- [強化学習モデル: 最尤推定](how-to-cognitive-modeling-rl1.html)　☆

- [強化学習モデル: ベイズ推定(1)](how-to-cognitive-modeling-rl2.html)　○

- [強化学習モデル: ベイズ推定(2)](how-to-cognitive-modeling-rl3.html)　○

- [強化学習モデル: ベイズ推定(3)（準備中）](how-to-cognitive-modeling-rl4.html)　○

- [強化学習事態でのベイズ推論モデル（準備中）](how-to-cognitive-modeling-rl5.html)　○

<br />

### 逐次サンプリングモデル

- [逐次サンプリングモデル：DDM(準備中)](how-to-cognitive-modeling-ssm1.html)　○

- [逐次サンプリングモデル: LBA(準備中)](how-to-cognitive-modeling-ssm2.html)　○

- [LBAモデルを用いた反応時間の解析](https://ykunisato.github.io/lbaStan/lbaStan.html)

- [LBAモデルを用いた反応時間の解析:階層ベイズ編](https://ykunisato.github.io/hlbaStan/hlbaStan.html)

<br />

### その他

- [hBayesDMでベイジアン認知モデリング](how-to-hBayesDM.html)

- [Rを用いたグラフィカルモデルの作成](how-to-graphicalModel.html)

- [latent cause model（開発中）](https://ykunisato.github.io/lcmr/)

<br />

## メタ分析

- [メタ分析](how-to-meta1.html)　☆

- [ネットワークメタ分析](how-to-meta2.html)　☆

<br />

## 心理ネットワークモデル

- [心理ネットワーク入門1](how-to-psychological-network1.html) ☆

- [心理ネットワーク入門2（準備中）](how-to-psychological-network2.html) ☆

- [微分方程式について](https://github.com/ykunisato/kunisato-lab-materials/blob/main/learning_ODE.md)(研究室限定資料)

<br />

## その他

- [電子ラボノートeLabFTWの導入方法](how-to-elabftw.html)

- [自動執筆量記録・報告システム](how-to-google-doc.html)

