---
title: "研究室の特色と進学希望者へ"
---
## 研究室の教育目標と特色

### 学部ゼミ

本研究室では，以下の教育目標をもってゼミ・講義を行っています。

- 臨床心理学の研究方法や考え方を理解し，卒業論文をまとめることができる。
- 認知行動療法の基礎を理解し，今後の生活の中でのセルフヘルプの１つとして，つかえるようになる。
- 実証に基づく医療・臨床心理実践の方法論を学び，今後の生活で医療関連情報を有効に活用できるようになる。

※ 夏にはゼミ合宿を予定しています。春には卒論構想発表会を予定しています。
 
<br />

### 大学院ゼミ

本研究室では，以下の教育目標をもってゼミ・講義を行っています。

- 臨床心理学の研究方法や考え方を理解し，修士論文をまとめることができる。
- 認知行動療法の基礎と臨床応用を理解し，今後の臨床実践に用いることができるようになる。
- 実証に基づく医療・臨床心理実践の方法論を学び，今後の臨床実践に用いることができるようになる。
 
+α（興味のある方は）

- 認知神経科学の方法を学び，研究に活用することができるようになる。
- 計算論的臨床心理学・計算論的精神医学の研究方法を学び，研究に活用することができるようになる。

※ 春に研究構想と臨床実践に関するゼミ合宿を予定しています。

<br />
<br />

## 計算論的臨床心理学研究室への進学を希望される方へ
 
計算論的臨床心理学研究室へ進学を考えておられる方は，一度，国里の研究室をご訪問下さい。 特に，他大学から受験を考えている方の場合は，国里や研究室の様子などを知ることが難しいかと思いますので，是非ともご活用下さい。また、大学院進学説明会も行われますので、研究室訪問を希望される場合は、進学説明会の前後の時間を活用いただけますと、効率的かと思います。

<br />

### 研究室訪問の流れ
1. 国里まで，研究室を訪問を希望する旨をご連絡ください（連絡にはメールフォームを活用ください）。
1. 相談の上で，研究室訪問の日程を決めます。
1. 決められた日程に，専修大学生田キャンパスの国里の研究室にお越し下さい。

- 入試の公平性を保つため、研究室訪問をご希望の方には大学院入試出願期間終了までにお越しいただいています（大学院入試出願期間終了から入試当日までの間は研究室訪問をお受けしておりません）。研究室訪問をご希望の方は、スケジュールに余裕をもってご連絡ください（あまりに直前の場合は日程調整ができない可能性もございます）。

- 専修大学以外の大学に在学中の方の場合は，連絡する前に指導を受けている先生にご相談することをオススメします。

- 研究室訪問時には，大学院で学びたい臨床の内容，行いたい研究の内容をお話していただくので，用意しておいてください。緊張してしまうことも多いので，聞いておきたいことをメモしてこられると安心かと思います。

- 研究室訪問は，入学選考や入学後の研究室配属とは無関係ですが，ご自身が学びたい臨床や行いたい研究ができるのか確認する機会としてご活用ください。
