---
title: "再生可能なデータ解析入門"
---

## 再生可能性とは？

研究における再現性を考える上で，Clarerbout, Jが提案したReplicabilityとReproducibilityの区分はとても便利です。Clarerbout, Jによると，

- Replicability(再現可能性) = 新規に取得したデータに同じ解析をして同じ結果が得られること
- Reproducibility(再生可能性) = 既存データに同じ解析をして同じ結果が得られること[^1]

とされます[^2]。Replicability(再現可能性) は，簡単に言うと新たに追試をして同じ結果が得られることです。これについては，これ以上このページでは扱いません。

　一方，Reproducibility(再生可能性)は，既に収集されたデータに対して，論文などで記載されている同じ解析を行った場合に，同じ結果が得られることです。再生が不可能な研究は，再現もしないと思われるので，まずは再生可能な研究ができることが前提になります。本ページの以降では，この再生可能なデータ解析について詳しく解説します。
　
<br />
<br />

## 再生可能なデータ解析のためにRを使おう！

　再生可能なデータ解析をする際の原則は，「データに対して行った操作をすべて記録する」です。これが可能なら，ExcelやSPSSなどを使っても全く問題はありません。つまり，これらのソフトの操作をするたびに，テキストエディタなどにすべての作業を記入し，それを第三者にもわかるようにしておけば良いです。ただ，これはかなり骨が折れます[^3]。なんで骨が折れるかというと，Excelなどでマウスを動かしてポチポチやった作業を記録するのですが，これが面倒です。面倒ですが，その記録がないと，生データから解析結果を得ることができなくなります（例えば，逆点処理・変数変換・データの除外をしたのに記録してないと結果は変わってきます）。

　そこで便利なのがRやPythonなどのオープンソースなプログラミング言語です[^4]。プログラムコードを書くのが面倒くさいなあと思われるかもしれませんが，インターネットで検索すれば，必ず優れた例や解説もあるので，すぐに慣れると思います。生データを読み込んで，それ以降Rなどで処理をすれば，その行った処理がすべて記録されます。ただ，Rのコンソールにそのまま書き込むと行った処理の記録になりませんので，R Markdownを使用することを強くおすすめします。

　Rでのコードの書き方やR Markdownの使い方などは，以下のスライドで詳しく解説しているので，参照してください。R Markdonwについては，[kazutanのサイト](https://kazutan.github.io/kazutanR/index.html)や[中京大学の高橋康介先生による「再現可能性のすゝめ 」]( https://www.amazon.co.jp/dp/4320112431/ref=cm_sw_em_r_mt_dp_U_wo9vDb0EMTZK9)を参照することを強くおすすめします。最近は，[github](https://github.com/)や[OSF](https://osf.io/dashboard)などで，データとコードが配布されていることも多くなりました。興味のある研究のデータやコードをダウンロードして，解析やRコードの書き方を学ぶのも実践的で良いかと思います。
　
<br />

<iframe src="//www.slideshare.net/slideshow/embed_code/key/wNlFMYILtIJT0X" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-77835559" title="統計解析の再現可能性を高める取り組み" target="_blank">統計解析の再現可能性を高める取り組み</a> </strong> from <strong><a href="//www.slideshare.net/YoshihikoKunisato" target="_blank">Senshu University</a></strong> </div>

<br />
<br />

## 急速なソフトウェア開発が再生性を低める

　RやR Markdownを使っていれば大丈夫かというとそうではなくて，Rなどのオープンソースソフトウェアは，急速に発展しており，どんどん新しいパッケージが発表されたり変更が加えられています。Rパッケージはgithub上で開発されていることもあり，それをみると何人もの人が共同しつつ目まぐるしいスピードで変更を加えているのがわかりますし，エラーがあればissueに報告され，直ちに修正されている様子も確認できます。そのような急速にソフトウェアが開発される状況を踏まえて，Epskamp(2019)は[^5]，再生可能性を低める脅威として以下のようなものを指摘しています。

- β版：よく使用されているけど，β版(よく0.x.xなどで表現される）のソフトも多い。しかし，β版は今後大きな変更が加えられる可能性があり，将来の再生性を低める可能性がある。

- アップデートと依存関係：ソフトが大きくアップデートされると再生性が低くなる。また，Rパッケージの多くは他のパッケージと依存関係にあるので，依存しているパッケージのどれかが変更されると芋づる式に再生性が低くなる可能性がある。

<br />

## 急速なソフトウェア開発による再生性低下を防ぐ方法

　Epskamp(2019)は，急速なソフトウェア開発に伴う再生性低下のために，以下のような解決方法を提案しています。

1. 安定版のソフトを使用する。Epskamp(2019)は，安定版のソフトか確認する指標として，以下の５点をあげている。
  - β版ではない。バージョン番号の最初に0がついてないか確認する。
  - 方法論研究で妥当性が確認されている。ソフトの使用法を説明したページなどに，妥当性を検討した論文の情報があるかどうか確認する。
  - ドキュメントやチュートリアルがしっかりある。
  - ソフトのメンテナンスが活発になされている。少なくとも２年以内にアップデートがなされていたか，もしくはメンテナンスをしている人が当該領域でポジションをまだ得ているか確認する。
  - ソースコードが公開されている。
2. 論文発表にあたって，データとコードを公開する。
3. 使用したソフトウェアパッケージの状態を再生できるようにする。

<br />

上記の1と2だけでは，急速に開発されるソフトウェア環境で再生性を担保することができないので，３が必要になります。使用したソフトウェアパッケージの状態を再生できるようにするためには，(1)Rパッケージのバージョン管理, (2)解析環境のコンテナ化を推奨します。(Epskamp, 2019)。

<br />

## Rパッケージのパッケージ管理

　一番シンプルな方法は，以下のようにsessionInfo()を実行して，使用しているRパッケージのバージョン情報を記録することです。sessionInfo()を実行することで，現在どういう環境で解析がなされたかが記録できます。

```{r}
sessionInfo()
```

　devtools::install_version()を使えば，sessionInfo()で記録されたのと同じバージョンのRパッケージをインストールすることができます。以下の例の場合は，古いバージョンのggplot2をインストールしています。詳しくは，[こちら](https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages)を参照ください。

```
devtools::install_version("ggplot2", version = "0.9.1")
```

　ただし，sessionInfo()+devtools::install_version()の組み合わせでは，Rパッケージの膨大な依存関係までは扱うことができないので，完全な環境の再現にはなりません。そこで，Rパッケージのバージョン管理では，現段階では，以下の３つのRパッケージを使うことを推奨します。それぞれ特徴はありますが，解析実施時or終了時のスナップショット(Rパッケージのバージョン情報などが含まれる)をとっておいて，後でその状態を再現するパッケージになります。

- checkpoint: [checkpointの解説記事](https://cran.r-project.org/web/packages/checkpoint/vignettes/checkpoint.html)

- renv: [renvの日本語解説資料](https://qiita.com/okiyuki99/items/688a00ca9a58e42e3bfa)

- packrat: [packratの日本語解説資料](https://qiita.com/uri/items/5d473a5df91954585e62)

<br />

　しかし，そもそもOSが違うとかR本体の大きな変更があった場合は，これらのパッケージのバージョン管理だけでは，解決することはできません（古いRをいれればいいとかもありますが，面倒ですね・・・）。OSやR本体の変更も含めた再生性の確保をする場合は，次で説明する解析環境のコンテナ化が必須です。

## 解析環境のコンテナ化

　OSやRのバージョンなどが違っても再生性を担保するには，仮想環境を作って，そこにOSやソフトを用意するという方法があります。ただ，これだとかなり容量が大きくなるので，Dockerが提供するコンテナ技術を使って，最小限の構成でRを使った解析環境を作って，後で利用できるようにすることを推奨します。なんとなく難易度が高そうですが，ユーザーは作業が少なくて済むので，おすすめです。また，RStanやJAGSなどの準備が面倒だったり，難しいと感じるユーザーは，既に準備されたDockerを使えば，お手軽に解析環境を準備することができます。以下は，私が作成したRStudioを使った解析用Dockerのリストです。ベースのpaper-rを使用すれば，すぐにstanやJAGSが使えます。

- [心理学で使うRパッケージの入ったRStudio Docker](https://hub.docker.com/r/ykunisato/paper-r) (日本語環境対応版は，[こちら](https://hub.docker.com/r/ykunisato/paper-r-jp))

- [認知モデリング用RStudio Docker](https://hub.docker.com/r/ykunisato/cog-model-r)

- [心理学的ネットワークモデリング用RStudio Docker](https://hub.docker.com/r/ykunisato/psynet-r)

- [ネットワークメタ分析用RStudio Docker](https://hub.docker.com/r/ykunisato/netmeta-r)

- [上記が全部入ったラボ用RStudio Docker](https://hub.docker.com/r/ykunisato/ccp-lab-r)

<br />

### Dockerの始め方

使用はとっても簡単で，以下の５ステップで利用可能です。

1.Docker Desktop ( https://www.docker.com/products/docker-desktop )をインストールする。

2.ターミナル（Macの場合。Winはコマンドプロンプト)を開く

3.ターミナルに以下を打ち込んで、コンテナーをrunする(runの前にPullが自動的なされます)。パスワードとコンテナ名はご自身の好きなように設定ください。

```
docker run -e PASSWORD=好きなパスワード -p 8787:8787 -v ~:/home/rstudio -d --好きなコンテナ名 ykunisato/国里のDockerHubで使いたいコンテナ名
```

4.ブラウザを開いて，urlバー（アドレスバー）に，http://localhost:8787/ とタイプする

5.ブラウザ上にRstudioが出てくるので，IDにrstudio，パスに上記で設定したパスワードをいれる。

### Dockerの保存・配布方法

　国里のDocker hubに登録されているDockerはちょくちょく変更されます（ベースにしているrockerの変更があった場合，国里が気まぐれに変更した場合など）。そのため，解析が一段落したら，その現在使っているコンテナごと保存しておく必要があります。まず，解析で使っているコンテナのCONTAINER IDを確認します。確認には，ターミナルに以下のコマンドを打ち込んでください。  
```
docker ps -a
```

　CONTAINER IDが分かったら，以下のコマンドを打ち込んで，使っているコンテナをイメージ（保存しやすくまとめる程度の理解で良いと思います）にします。例えば，私の使っているコンテナ(IDはb1c05f9a452)をcog190817という名前でイメージ化する場合は，"docker commit b1c05f9a452 cog190817"と打ち込みます。

```
docker commit コンテナのID 好きな名前+日付
```

　次に，以下のコマンドを打ち込んで，作成したイメージを保存します（形式はtar）。
例えば，先程作成したイメージのcog190817を保存する場合は，"docker save cogModel190817 > cogModel190817.tar"と打ち込みます。まあまあ大きなサイズのファイルが保存されると思います（国里のDockerを使っている場合は，4GBを超えると思います）。これを保存しておけば，後で同じ環境で解析が実施できたり，配布すれば第三者が確認することもできます。

```
docker save 上で付けた名前 > 好きな名前.tar
```

### 保存・配布したDockerの利用方法

　tar形式で保存できたら，今度使うときは，ターミナルに以下のコマンドで読み込みます。先程の例の場合は，"docker load < cogModel190817.tar"です。

```
docker load < 上で付けた名前.tar
```
　"docker ps -a"を打ち込んで，上記のコマンドにより読み込まれた内容を確認します。REPOSITORYの列でリポジトリ名を確認します。そのリポジトリ名を使って，以下のようにrunをします（パスワードやコンテナ名は好きに設定する）。

```
run -e PASSWORD=パスワード -p 8787:8787 -v ~:/home/rstudio -d --name コンテナ名 リポジトリ名
```

ファイルサイズが大きめなのが悩ましいですが，これだと時間が経っても再生可能な形式で保存・配布が可能です。

<br />
<br />

[^1]: ReproducibilityとReplicabilityの定訳はないと思います。どちらも再現可能性と訳されることもありますが，意味は違いますので，Reproducibilityを再生可能性，Replicabilityを再現可能性と分けて訳してみました。翻訳にあたり，すでに再現実験などの言葉が日本語として定着しており，再現性には追試のニュアンスがあることから，Replicabilityを再現可能性と訳しました。そして，Reproducibilityは再現という言葉を避けて，すでに得られたデータから同じ結果を繰り返すことができるかというニュアンスを含めるために，再生可能性と訳しました。これは国里が2017年からなんとなく使っている翻訳なので，正式な翻訳やもっと良い翻訳があれば修正したいと考えています。

[^2]:Goodman, S. N. et al. 2016 What does research reproducibility mean? Science Translational Medicine, 8(341), 341ps12.[link](https://stm.sciencemag.org/content/8/341/341ps12.full)

[^3]: 私は，データに対して強迫的な傾向があるので，Rを本格的に導入する前は，すべてテキストエディタに記載していました。ただ，人間なので，どこかでエディタへのメモ記載を忘れることがあります。そうすると，また，最初からデータを処理し直したりしており，えらい無駄に時間をかけていました（データ解析版賽の河原の石積み）。こういう再生可能性への関心が高まってきて，ずいぶんと便利になってきました。

[^4]: RでもPythonでも良いのですが，データ解析のみの場合は，Rの方が便利と思います。また，インターネットで調べた時に，心理学関連の解析であれば，Rの方が圧倒的に情報が多いと思います。

[^5]:Epskamp, S. (2019). Reproducibility and Replicability in a Fast-Paced Methodological World. Advances in Methods and Practices in Psychological Science, 2(2), 145-155. [link](https://journals.sagepub.com/doi/full/10.1177/2515245919847421), [preprint](https://psyarxiv.com/cnq4d/)



