---
title: "お知らせ"
---

### 2022

- 2022/3/31 例によって，お知らせ完全に放置していました。ただ，HPは随時アップデートしています。


### 2021

- お知らせ完全に放置していました。HPは随時アップデートしています。

### 2019

- 4/1から１年間，国里がUniversity of AmsterdamのPsychological Methodsに在外研究します。

### 2018

- 心理学評論に「臨床心理学と認知モデリング」についての論文が掲載されました。論文PDFなどは[こちら](https://kunisatolab.github.io/main/articles-japanese.html)から。

- 2018/1/3 HPを少しだけ更新しました。RStudioでの管理をしやすくするために少しだけURLが変わりました。

### 2017

- 2017/5/9 長谷川晃先生(東海学院大学人間関係学部)の論文が Journal of Rational-Emotive & Cognitive-Behavior Therapy誌にアクセプトされました。
- 2017/4/4 放置していまったHPをアップデートし，Githubに移転しました。

### 2016

- 2016/9/12 また放置しましたが、ちょっとアップデートしました。
- 2016/3/31 しばらく放置していましたが、ちょっとアップデートしました。

### 2015

- 2015/9/27 研究業績をアップデートしました。また、PsychoPyを自習するための課題をgithubに公開しました。
- 2015/4/1 HPをアップデートしました。新学期が始まります。
- 2015/1/6 早稲田大学大学院人間科学研究科の小川祐子さんの研究が心身医学に採択されました。補完代替療法をうける外来がん患者が主治医と話す際のためらいについて検討いした研究になります。

### 2014

- 2014/6/19 町野先生（広島大学精神神経医科学）の論文がJournal of Affective Disorders誌にアクセプトされました。治療抵抗性のうつ病患者の反芻に関わる脳部位をVoxel-based morphometry (VBM)を用いて検討した研究になります。
- 2014/6/12 早稲田大学大学院人間科学研究科の巣山晴菜さんの研究が不安障害研究に採択されました。社交不安障害患者におけるうつ症状と拒絶過敏性が社交不安症状に及ぼす影響を検討した研究になります
- 2014/6/2 研究室訪問についてアップデートをしました。
- 2014/3/9 地味にHPの写真などをアップデートしました。徐々に新学期にむけて準備です。

### 2013

- 2013/12/25 吉野先生（広島大学）の論文がPsychiatry Research: Neuroimaging誌にアクセプトされました。慢性疼痛患者を対象にして、安静時fMRIを用いてReHo（局所的な均質性）を検討したものになります。
- 2013/9/24 後期がスタートしたので，研究業績をアップデートして，新たに「研究メモ」を追加しました。Presentationに関するメモもアップしました。
- 2013/9/7　「ストレス科学」に「うつとストレスに対する計算論的アプローチ：計算論的精神医学入門」が掲載されました。
- 2013/7/23 専修大学シンポジウムシンポジウム，「不安、うつ、妄想に挑む心理学 : 臨床と基礎の融合を目指して 」の講演録が公開されました。
- 2013/6/1 プロフィールの職歴と学会委員を更新しました。
- 2013/5/27 小関先生の論文がJournal of Affective Disorders誌にアクセプトされました。内容は，NIRSをもちいて測定した，うつ病患者の言語流暢性課題時の前頭・側頭の血流量と自動思考との関連の検討したものであり，うつ病のNIRS研究で認知行動療法にかかわるコンポーネントを検討した研究になります。
- 2013/4/1 専修大学人間科学部心理学科に赴任しました。