---
title: "国内学会・研究会発表"
---

## 2020

### ポスター発表

### 口頭発表・シンポジウム・研究会

- 国里愛彦 (2020). 日心企画「再現可能な心理学研究入門」企画者 日本心理学会第84回大会  東京　WEB開催　2020年11月1日														
- [117] 国里愛彦・竹林由武 (2020). チュートリアル・ワークショップ「今日からできる再現可能な論文執筆」 日本心理学会第84回大会  東京　WEB開催　2020年10月31日

- [116] 国里愛彦 (2020). WS「臨床研究の方法論と倫理（臨床実践における倫理を含む）」　日本認知・行動療法学会第46回大会　広島　WEB開催　2020年9月11日から9月30日

- [115] 国里愛彦 (2020). 計算論的アプローチからみた抑うつと認知行動療法　大会企画シンポジウム「抑うつ研究の最前線」 話題提供　日本認知・行動療法学会第46回大会　広島　WEB開催　2020年9月11日から9月30日

- [114] 国里愛彦 (2020). 計算論的アプローチ　自主企画シンポジウム「認知行動療法研究の新時代を切り開く研究法」　話題提供　日本認知・行動療法学会第46回大会　広島　WEB開催　2020年9月11日から9月30日

- [114] 樫原　潤・竹林由武・国里愛彦・伊藤正哉 (2020). うつ病・不安障害の分類可能性と症状ネットワーク構造の検討―Gaussian graphical mixture モデルに基づく潜在ネットワーク・クラス分析―　　日本心理学会第84回大会  東京　WEB開催　2020年9月8日-11月2日

- [113] 井上のどか・飯島雄大・国里愛彦 (2020). ストレス対処方略としての食行動による気分の認知の変化について　日本心理学会第84回大会  東京　WEB開催　2020年9月8日-11月2日

- 国里愛彦 (2020). 日本心理学会若手の会企画シンポジウム「若手が聞きたい再現可能性問題の現状とこれから」指定討論　日本心理学会第84回大会  東京　WEB開催　2020年9月9日　

- 国里愛彦 (2020).オープンサイエンスの動向と計算論的アプローチ 第25回計算論的精神医学コロキウム NCNP 2020年1月24日(WEB経由で発表)

※ 以下は当日の発表スライドから計算論的アプローチの部分を削除した内容です。

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vStKDpYXXMYq_KkFcTcct8Xhhup3nL_dSIIGH27fin4Nv8ohz11xfqso6UEWQqGMlaIgkIPdf7qs_3_/embed?start=false&loop=false&delayms=30000" frameborder="0" width="480" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## 2019

### ポスター発表

- [112] 長谷川 晃・杣取 恵太・西村 春輝・服部 陽介・国里 愛彦(2019). 衝動的行為と反すうが抑うつを強める過程: 行動的衝動性に対する潜在変数アプローチを適用して 日本心理学会第83回大会　大阪(茨木)　立命館大学大阪いばらきキャンパス　2019年9月11日 [優秀発表賞]

## 2018

### ポスター発表

- [111] 長谷川晃・杣取恵太・西村春輝・服部陽介・国里愛彦(2018). 質問紙と実験課題で測定された衝動性の関連：行動的衝動性に対する潜在変数アプローチを適用して　日本認知・行動療法学会第44回大会　東京(品川)　明治学院大学白金キャンパス　2018年10月27日

- [110] 中川卓知・国里愛彦(2018). 抑うつとリスクテイキング行動との関連：Automatic BARTに対するベイジアン認知モデリングの適用　日本認知・行動療法学会第44回大会　東京(品川)　明治学院大学白金キャンパス　2018年10月27日

- [109] 下野有紀・長谷川晃・土原浩平・国里愛彦(2018). 大学生用ひきこもり親和性尺度の作成　日本認知・行動療法学会第44回大会　東京(品川)　明治学院大学白金キャンパス　2018年10月27日


- [108] 土原浩平・石金浩史・国里愛彦(2018). マインドフルネスと痛みの関連　日本認知・行動療法学会第44回大会　東京(品川)　明治学院大学白金キャンパス　2018年10月28日


- [107] 井口聖香・大久保街亜・国里愛彦(2018). 新たな過剰適応傾向尺度作成の試み　日本認知・行動療法学会第44回大会　東京(品川)　明治学院大学白金キャンパス　2018年10月28日

- [106] 畑琴音・小川祐子・小野はるか・竹下若那・国里愛彦・鈴木伸一(2018). がん患者用活動抑制尺度（Sickness Impact Profile for Cancer Patients）開発の試み―経過報告　第31回日本サイコオンコロジー学会総会抄録集，201.


### 口頭発表・シンポジウム・研究会

- 国里愛彦 (2018). 教育講演「単一事例研究法と統計的推測：ベイズ流アプローチを架け橋として（講師：竹林由武）」　座長　日本認知・行動療法学会第44回大会　東京(品川)　明治学院大学白金キャンパス　2018年10月28日

- 国里愛彦　(2018). 公募シンポジウム「心理学における機械学習アプローチの可能性」　司会　日本心理学会第82回大会　仙台　仙台国際センター　2018年9月25日

- [105] 国里愛彦　(2018). ベイズ統計から見た新たな健康アセスメントとその評価　日本健康心理学会記念出版委員会企画シンポジウム「健康心理アセスメントの新たな可能性」　話題提供　日本健康心理学会 第31回大会 京都　京都橘大学　2018年6月23日

## 2017

### ポスター発表

- [104] 竹林 唯・巣山晴菜・伊藤理紗・国里愛彦・鈴木伸一・前田正治(2017). 不安症状と遅延または労力を伴う価値割引の関連の検討　第９回日本不安症学会学術大会　福岡　九州大学医学部百年講堂　2017年3月10日

- [103] 小野はるか・小関俊祐・国里愛彦・鈴木伸一　(2017).　小１プロブレム支援方略としての保育士コンサルテーションの有効性　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [102] 土原浩平・国里愛彦・長谷川晃　(2017).　マインドフルネスと攻撃性の関連における注意制御・視点取得の調整効果　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [101] 小川祐子・小澤美和・国里愛彦・鈴木伸一　(2017).　親の病気を子どもに伝える困難感を抱えやすいがん患者の特徴　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [100] 佐藤秀樹・岡本文子・伊藤理紗・国里愛彦・鈴木伸一　(2017).　反芻がエフォートフル・コントロールと回避行動を媒介して抑うつに及ぼす影響　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [99] 伊藤理紗・佐藤秀樹・国里愛彦・鈴木伸一　(2017).　オーギュメンテッドリアリティを用いた，恐怖の行動評定方法の作成　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [98] 金子美帆・国里愛彦　(2017).　日本語版能動的先延ばし尺度の作成と信頼性・妥当性の検討　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [97] 竹下若那・小川祐子・小野はるか・畑　琴音・佐藤秀樹・市倉加奈子・松永美希・国里愛彦・鈴木伸一　(2017).　大学生の非致死性トラウマ体験者におけるストレスコーピングと主観的幸福感の関連　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [96] 土谷美月・岡田謙介・国里愛彦　(2017).　不確実さの強化率の変化を追加したCPP課題の作成　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

- [95] 菊池羽音・澤幸祐・国里愛彦　(2017).　外傷後認知の時系列的変化を測定するための方法の検討-トラウマフィルムパラダイムにドット判断手続きを加えた課題作成と経験サンプリング法による外傷後認知の測定-　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月30日

- [94] 坂本次郎・国里愛彦　(2017).　Webアプリケーションを用いた経験サンプリング自動調査システムの構築　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月30日

- [93] 杣取恵太・国里愛彦　(2017).　恐怖条件づけにおける実験パラメータの検討：恐怖顔および叫び声を無条件刺激とした恐怖条件づけに必要な実験環境について　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月30日

- [92] 畑　琴音・近藤夏生・副島紗彩・小川祐子・小野はるか・国里愛彦・鈴木伸一　(2017).　乳がんサバイバーのソーシャル・サポートに関する質的研究―PTGとの関連をふまえて―　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月29日

### 口頭発表・シンポジウム・研究会

- [91] 国里愛彦(2017). ベイジアン・モデリングと計算論的臨床心理学　日本社会心理学会 第4回春の方法論セミナー「効果の科学からデータ生成過程の科学へ～心理学者のためのベイジアン・モデリング入門」，上智大学，2017年3月14日

- 国里愛彦(2017). ベイズ統計の基礎　研究会「臨床疫学研究における報告の質向上のための統計学の研究会」,東京医科歯科大学, 2017年3月18日 

- 国里愛彦(2017). 統計解析の再現可能性を高める取り組み　研究会「臨床疫学研究における報告の質向上のための統計学の研究会」,東京医科歯科大学, 2017年7月8日 

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTySEMxqNr-FrwAAbnJWm4gza2hkWQGbU-wI_3P0kHPFGGsrCt6EFjxcVNs3OP4OHYGYM8dA-AbT2lS/embed?start=false&loop=false&delayms=30000" frameborder="0" width="480" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

- [90] 国里愛彦　(2017). 公募シンポジウム「明日からできる経験サンプリング法-効率的なデータ収集と洗練した解析で移ろう心を描き出す-」　企画・司会・企画趣旨説明　日本心理学会第81回大会 久留米 久留米シティプラザ　2017年9月20日

- 国里愛彦　(2017).小講演「適応的な自己注目:自己反芻と対比した自己内省の機能と性質の検討（講演者：森正樹）」　司会　日本心理学会第81回大会 久留米 久留米シティプラザ　2017年9月20日

- [89] 国里愛彦　(2017). 計算論的臨床心理学からみたウェルビーイング　公募シンポジウム「ウェルビーイングの科学と実践:臨床ポジティブ心理学の展開(1)」　話題提供　日本心理学会第81回大会 久留米 久留米シティプラザ　2017年9月22日

- 国里愛彦　(2017).　自主企画シンポジウム7「臨床実践と研究に活かすベイズ統計学」　企画者　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月30日

- 国里愛彦　(2017).　教育講演「認知と行動のあいだを連合学習理論で整理する（講演者：澤幸祐）」　座長　日本認知・行動療法学会第43回大会　新潟 朱鷺メッセ（新潟コンベンションセミナー）　2017年9月30日

## 2016
### ポスター発表

- [88] 小田島裕佳・下斗米淳・国里愛彦(2016).社交不安傾向と低空間周波数画像に対する回避傾向との関連　日本認知・行動療法学会第42回大会　徳島 アスティとくしま　2016年10月9日

- [87] 金子美帆・国里愛彦(2016). 価値割引パラダイムを用いた先延ばしの測定―回避・衝動性の観点から―. 日本認知・行動療法学会第42回大会 徳島 アスティとくしま　2016年10月9日

- [86] 菊池羽音・村松 励・国里愛彦 (2016). 原因帰属スタイルに着目したADHD児の二次障害予防の検討 ー行動の統制感，抑うつ，ADHDスクリーニング尺度を用いてー　日本認知・行動療法学会第42回大会 徳島 アスティとくしま　2016年10月9日

- [85] 坂本次郎・杣取恵太・国里愛彦 (2016). 日常場面における痛みと痛みの変動性が抑うつおよび破局的試行に与える影響ー集中縦断データと線形ベイズモデルを用いた検討ー　日本認知・行動療法学会第42回大会 徳島 アスティとくしま　2016年10月9日
 
- [84] 杣取恵太・下斗米淳・国里愛彦 (2016). 命題アプローチにおける恐怖条件づけの学習過程―Rescorla-Wargner モデルを用いた推定―　日本認知・行動療法学会第42回大会 徳島 2016年10月9日

- [83] 土谷美月・国里愛彦 (2016). スチューデント・アパシーと認知コントロールの関連ー切替情動ストループを用いてー 日本認知・行動療法学会第42回大会　徳島 アスティとくしま 2016年10月9日
 
- [82] 横光健吾・田山　淳・高田琢弘・甲田宗良・金澤潤一郎・国里愛彦・高橋髙人・高橋　史・古川洋和・松岡紘史（2016）大学生における病的ギャンブリング症状の潜在構造：taxometric analysisを用いて　第51回日本アルコール・アディクション医学会学術総会プログラム・講演抄録集，179頁，10月，船堀．
 
### 口頭発表・シンポジウム・研究会

- [81] 国里愛彦 (2016). 臨床心理学研究におけるサンプルサイズ設計　日本パーソナリティ心理学会　アフター・カンファレンス企画（共催：日本社会心理学会）「統計セミナー　心理学研究におけるサンプルサイズ」　兵庫　関西学院大学西宮ケ原キャンパス　2016年9月16日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/5dom2KWGB5ZnVK" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-66093260" title="臨床心理学における例数設計" target="_blank">臨床心理学における例数設計</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>


- 国里愛彦　(2016). 自主企画シンポジウム「連合学習理論の展開と臨床との接点」　企画・司会　日本認知・行動療法学会第42回大会 徳島 アスティとくしま　2016年10月10日

- [80] 国里愛彦　(2016). 計算主義者からみた認知行動療法　大会企画シンポジウム「認知行動療法における神経科学的知見の応用可能性」　日本認知・行動療法学会第42回大会 徳島 アスティとくしま　2016年10月9日
 
## 2015
### ポスター発表

- [79] 兼子唯・巣山晴菜・国里愛彦・伊藤理紗・鈴木伸一　2015　不安からの回避・逃避行動の分類の検討　第7回日本不安症学会学術大会　広島　2015年2月15日(抄録集P137)
 
- [78] 吉村普平・岡本泰昌・松永美希・国里愛彦・小野田慶一・鈴木伸一・山脇成人　2015　うつ病に対する認知行動療法における内側前頭前野：　前帯状回間の機能的結合性の変化について　日本心理学会第79回大会　名古屋　名古屋国際会議場　2015年9月24日

- [77] 杣取恵太・下斗米淳・国里愛彦 2015 新たなメタ認知課題の作成と妥当性の検討 日本認知・行動療法学会第41回大会　仙台 仙台国際センター　2015年10月2日

- [76] 小田島裕佳・佐々木彩・国里愛彦・熊野宏昭　2015 注意バイアス修正課題の教示内容が社交不安と背外側前頭前野の総ヘモグロビン濃度に及ぼす影響：近赤外線分光法を用いた検討　日本認知・行動療法学会第41回大会　仙台 仙台国際センター　2015年10月2日

- [75] 坂本次郎・大久保街亜・国里愛彦　2015 抑うつにおける痛みの将来予測と意思決定：計算論アプローチによる意思決定過程の検討　日本認知・行動療法学会第41回大会　仙台 仙台国際センター　2015年10月3日

- [74] 時田椋子・坂本次郎・杣取恵太・澤幸祐・国里愛彦　2015 経験サンプリングにおける喫煙に渇望が与える影響：系統的レビューとメタアナリシス　日本認知・行動療法学会第41回大会　仙台 仙台国際センター　2015年10月3日

- [73] 兼子　唯・巣山晴菜・国里愛彦・伊藤理紗・鈴木伸一　2015　安全確保行動からネガティブ情動への影響の検討，日本認知・行動療法学会第41回大会　仙台 仙台国際センター　2015年10月
 
- [72] 髙垣耕企・岡本泰昌・神人　蘭・森　麻子・西山佳子・山村崇尚・横山仁史・塩田翔一・岡本百合・三宅典恵・尾形明子・国里愛彦・川上憲人・古川壽亮・山脇成人 (2015). 青年期閾値下うつを対象とした短期行動活性化の効果：無作為化比較試験　第12回日本うつ病学会総会, 249頁.　[第10回うつ病学会学会奨励賞受賞]
 
### 口頭発表・シンポジウム・研究会

- [71] 国里愛彦・杣取恵太 (2015)　連合学習理論と不安症　シンポジウム「不安障害の心理学基礎研究と認知行動療法」　第7回日本不安症学会学術大会　広島　2015年2月15日 (抄録集では杣取恵太の名前が抜けていますが共同発表になります)

<iframe src="//www.slideshare.net/slideshow/embed_code/key/EXpQwunjWmtCOW" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-74207095" title="連合学習理論と不安症 " target="_blank">連合学習理論と不安症 </a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>

- 国里愛彦(2015). 心理職のための神経科学（脳科学）入門　臨床心理フロンティア研修会　東京　2015年5月8日

<iframe width="560" height="315" src="https://www.youtube.com/embed/jktV73DpA_w" frameborder="0" allowfullscreen></iframe>

- 国里愛彦(2015). PROMISの取り組み　研究会「臨床疫学研究における報告の質向上のための統計学の研究会」,東京医科歯科大学, 2015年7月25日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/20K1qz7HuTJdhG" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/promisirt" title="PROMISの取り組み（IRTを使った項目バンク作成）" target="_blank">PROMISの取り組み（IRTを使った項目バンク作成）</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>
 
- [70] 国里愛彦 (2015).　論文作成における尺度開発の方法と実際　機関誌編集委員会企画シンポジウム　日本健康心理学会第28回大会　東京　桜美林大学 2015年9月5日　
 
- 国里愛彦 (2015).　介入効果のメタ分析　公募シンポジウム「現場に役立つ心理学(5)： 研究・実践の効果を測定するための研究デザインとデータ分析」　日本心理学会第79回大会　名古屋　名古屋国際会議場 2015年9月22日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/5BJ6dojVhhNn8f" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-73968064" title="介入効果のメタ分析" target="_blank">介入効果のメタ分析</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>

- [69] 国里愛彦 (2015).　うつ病の反すうに関する脳画像研究　公募シンポジウム「反すう研究の最前線: 国内で行われた研究を中心に」日本心理学会第79回大会　名古屋　名古屋国際会議場 2015年9月23日


- 国里愛彦 (2015).　複雑な臨床的問題を階層ベイズで解く　専修大学心理科学研究センターシンポジウム「融合的心理科学の創成：心の連続性を探る」　東京　専修大学神田キャンパス 2015年10月24日

<iframe width="560" height="315" src="https://www.youtube.com/embed/LGLbOO05HkI" frameborder="0" allowfullscreen></iframe>

## 2014
### ポスター発表

- [68] 兼子唯・巣山晴菜・国里愛彦・伊藤理紗・鈴木伸一　2014　不安と気分変動の関連の検討　第20回日本行動医学会学術総会　所沢　2014年11月22日-23日 (抄録集P83)
 
- [67] 矢田さゆり・巣山晴菜・兼子　唯・清水　馨・国里愛彦・鈴木伸一　2014　職場において他者評価で捉えられるうつ症状の兆候尺度の検討　第21回日本行動医学会学術総会 所沢　2014年11月22日-23日 (抄録集P75)
 
- [66] 時田椋子・国里愛彦・松永美希(2014). 抑うつと強化感受性・他者依存性との関連 日本認知・行動療法学会第40回大会　富山　2014年11月３日
 
- [65] 坂本次郎・国里愛彦・田中信利(2014). 解釈バイアスと否定的・肯定的な将来予期の関連　日本認知・行動療法学会第40回大会　富山　2014年11月３日
 
- [64] 兼子　唯・巣山晴菜・国里愛彦・伊藤理紗・鈴木伸一(2014). 日常生活内における安全確保行動がネガティブ感情に与える影響の検討　日本認知・行動療法学会第40回大会　富山　2014年11月３日
 
- [63] 杣取恵太・国里愛彦・村松　励 (2014). 自己愛パーソナリティの誇大特性と過敏特性が非行に与える影響－共感性との関連－　日本認知・行動療法学会第40回大会　富山　2014年11月２日
 
- [62] 鈴木彩夏・国里愛彦・下斗米　淳 (2014). Dispositional Envy ScaleおよびEpisodic Envy Scaleの日本語版作成と信頼性・妥当性の検討 日本心理学会第78回大会　京都　2014年9月11日
 
### 口頭発表・シンポジウム・研究会

- 国里愛彦(2014). シンポジウム「うつ病の認知行動科学研究の最前線とそれに基づく新たな臨床アプローチ」　企画・座長　第21回日本行動医学会学術総会　所沢　2014年11月22日
 
- [61] 国里愛彦(2014). 介入研究の質のアセスメント：GRADEシステム　シンポジウム「失敗しない研究計画入門：研究の質を評価するための国際基準の理解」日本認知・行動療法学会第40回大会　富山　2014年11月2日


<iframe src="//www.slideshare.net/slideshow/embed_code/key/1cUjBN4N112Vh1" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-40896238" title="介入研究の質のアセスメント" target="_blank">介入研究の質のアセスメント</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>
 
- 国里愛彦(2014). 「診断精度のメタ分析」の書き方　研究会「臨床疫学研究における報告の質向上のための統計学の研究会」,東京医科歯科大学, 10月25日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/2sDLeFUudrw2kh" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-40713224" title="診断精度研究のメタ分析" target="_blank">診断精度研究のメタ分析</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>
 
- 国里愛彦(2014). 臨床試験における欠測発生の予防法　研究会「臨床疫学研究における報告の質向上のための統計学の研究会」,東京医科歯科大学, 3月16日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/YOnVsXLPu4XYe" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-32359370" title="臨床試験における欠測発生の予防法" target="_blank">臨床試験における欠測発生の予防法</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>
 
## 2013
### ポスター発表

- [60] 小川祐子・武井優子・古賀晴美・島田真衣・長尾愛美・佐々木美保・国里愛彦・谷川啓司・鈴木伸一 (2013). 診察場面において主治医との会話をためらう患者の特徴 第26回日本サイコオンコロジー学会総会　大阪　2013年9月20-21日(抄録集p. 143)．
 
- [59] 小関俊祐・小関真実・国里愛彦(2013). 児童の抑うつに影響を及ぼす行動活性化の効果　日本心理学会第77回大会　札幌　2013年9月21日（プログラム集p395）
 
- [58] 岡山紀子・宣 聖美・矢田さゆり・兼子 唯・巣山晴菜・清水 馨・国里愛彦・鈴木伸一(2013). 関係性に焦点をあてた職場におけるコミュニケーション改善プログラムによる職位別のストレス低減効果の差異 第13回日本認知療法学会　東京　2013年8月24日（プログラム集p.?）

- [57] 岡山紀子・宣 聖美・矢田さゆり・兼子 唯・巣山晴菜・清水 馨・国里愛彦・鈴木伸一(2013). 集団メンバー間の関係性に焦点をあてた職場におけるコミュニケーション改善プログラムが職場のストレ スに与える影響 日本行動療法学会 第39回大会　東京　2013年8月25日（プログラム集p.?）
 
- [56] 小川祐子・武井優子・島田真衣・長尾愛美・佐々木美保・国里愛彦・谷川啓司・鈴木伸一 (2013).　診察場面において主治医に話すことに対するためらい尺度の開発　第19回日本行動医学会学術総会　東京　2013年3月8-9日 (抄録集p.123)
 
- [55] 伊藤理紗・兼子唯・巣山晴菜・国里愛彦・吉田栄治・貝谷久宣・鈴木伸一(2013). SAD患者における人間関係の特徴とSAD症状との関連　第19回日本行動医学会学術総会　東京　2013年3月8-9日 (抄録集p.124) 

- [54] 伊藤理紗・巣山晴菜・兼子唯・伊藤大輔・国里愛彦・島田真衣・横山仁史・吉田栄治・貝谷久宣・鈴木伸一 (2013). 曖昧な場面の肯定・中性・否定的解釈がSAD症状に及ぼす影響―健常群と臨床群からの検討―　第５回日本不安障害学会学術大会　札幌　2013年2月2-3日(抄録集p. 87)
 
### 口頭発表・シンポジウム・研究会

- 国里愛彦(2013). 第13回日本認知療法学会・日本行動療法学会 第39回大会合同企画シンポジウム「不安に関する基礎理論の最前線と臨床への還元」　座長　日本行動療法学会 第39回大会　東京　2013年8月24日
 
- 国里愛彦(2013). 自主企画シンポジウム「自動思考とは何か？」司会　 第13回日本認知療法学会　東京　2013年8月25日
 
- 国里愛彦 (2013).　Neural mechanisms of Cognitive Behavioral Therapy for depression 　専修大学心理科学研究センターシンポジウム「Development and current situations of
Cognitive Behavioural Therapy for children and/or persons with disabilities」　東京　専修大学神田キャンパス 2013年8月31日

- [53] 国里愛彦(2013). 自主企画シンポジウム「うつ病の発症および再発予防への認知行動療法の貢献」　話題提供「うつ病に対する認知行動療法の神経基盤」　日本心理学会第77回大会　札幌　2013年9月19日
 
- 国里愛彦(2013). チュートリアルワークショップ「自己報告式心理尺度の信頼性と妥当生における新しい国際基準」　講師（お手伝い）　日本心理学会第77回大会　札幌　2013年9月20日
 
- [52] 国里愛彦(2013). 自主企画シンポジウム「アナログ研究の新展開」　話題提供「臨床研究に繋がるアナログ研究-RDoCを意識した研究設計-」　日本心理学会第77回大会　札幌　2013年9月20日
 
- [51] 国里愛彦(2013) シンポジウム「社会に貢献できる心理生物学的研究」話題提供「うつ病と認知行動療法の作用機序に関する認知神経科学研究」　第29回日本ストレス学会学術総会　徳島　2013年11月8日
 
- 国里愛彦(2013).　反応性と解釈可能性の評価　研究会「心理・医学系研究者のためのデータ解析環境Rによる統計学の研究会」,東京医科歯科大学,　5月18日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/xvahIwlEgYTcqj" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-37480140" title="反応性と解釈可能性の評価" target="_blank">反応性と解釈可能性の評価</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>

## 2012
### ポスター発表

- [50] 小川祐子・武井優子・佐々木美保・島田真衣・長尾愛美・国里愛彦・鈴木伸一・谷川啓司(2012).　がん患者の抱える抑うつ症状に対する認知行動療法：集団療法と個別療法のメタ分析　第25回日本バイオセラピィ学会学術集会総会　倉敷　2012年12月13日～14日 (抄録集p. 94)
 
- [49] 国里愛彦(2012). 安静時fMRIを用いたBig Five研究の動向とグラフ理論の利用―Network-based statisticを用いた検討― 日本パーソナリティ心理学会第21回大会　松江　2012年10月7日（プログラム集p.27)
 
- [48] 島田真衣・佐々木美保・武井優子・小川祐子・長尾愛美・尾城友美・松田敦子・堂園知恵・国里愛彦・鈴木伸一(2012). 心疾患患者の抱える抑うつ症状に対する心理的介入に関する研究展望 日本行動療法学会第38回大会　京都　2012年9月23日（抄録集p.318-319）
 
- [47] 岡山紀子・清水馨・田上明日香・伊藤大輔・巣山晴菜・横山仁史・国里愛彦・鈴木伸一(2012).　職場の組織風土が精神的健康とポジティブ側面に与える影響　日本行動療法学会第38回大会　京都　2012年9月23日（抄録集p.322-323）
 
- [46] 宣聖美・清水馨・田上明日香・伊藤大輔・巣山晴菜・横山仁史・国里愛彦・鈴木伸一(2012).　職場におけるストレス対処法が生産性、仕事や生活への満足度に及ぼす影響　日本行動療法学会第38回大会　京都　2012年9月23日（抄録集p.388-389）
 
- [45] 横山仁史・野田隆政・小関俊祐・国里愛彦・伊藤大輔・巣山晴菜・杉村有司・石原奈保子・清水悠・中澤佳奈子・鈴木伸一(2012).　ポジティブおよびネガティブな自動思考のバランスと脳機能の関連-多チャンネルNIRSを用いた検討- 日本行動療法学会第38回大会　京都　2012年9月23日（抄録集p.324-325）
 
- [44] 小川祐子・武井優子・佐々木美保・島田真衣・長尾愛美・堂園知恵・尾城友美・松田敦子・国里愛彦・鈴木伸一(2012). がん患者の抱える抑うつ症状に対する認知行動療法 第25回日本サイコオンコロジー学会総会　福岡　2012年9月21-22日 (抄録集p.144)
 
### 口頭発表・シンポジウム・研究会

- [43] 国里愛彦(2012). 神経科学からみたパーソナリティ心理学の未来 シンポジウム「パーソナリティ心理学の未来を探して」日本パーソナリティ心理学会第21回大会，松江，10月7日
 
- [42] 国里愛彦(2012).研究事例報告：日本のうつ病患者を対象にBDI-IIにおける臨床的有意性を検討した研究 ワークショップ「明日から使える臨床的有意性の指標：行動療法研究に求められる統計学」日本行動療法学会の第36回研修会，立命館大学，9月21日

<iframe src="//www.slideshare.net/slideshow/embed_code/key/3zov2z89I6uo0m" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/bdiii" title="BDI-IIについて臨床的有意性を調べた研究紹介" target="_blank">BDI-IIについて臨床的有意性を調べた研究紹介</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>
 
- 国里愛彦(2012). Computational approach to Neurology and Psychiatry シンポジウム「Ahmed Moustafa博士来日講演会」，早稲田大学応用脳科学研究所主催，早稲田大学，9月14日
 
- 国里愛彦(2012).「メタ・アナリシス」の入門 研究会「心理・医学系研究者のためのデータ解析環境Rによる統計学の研究会」，東京医科歯科大学，8月25日

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRD1R5yRiru8JJbm6TCvSZr16jOA01I0mZHd86v7CFDKrQ7ltoENxuik5MJ9Mz1Q7b4_AJ_E8TciptA/embed?start=false&loop=false&delayms=30000" frameborder="0" width="480" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
 
- 国里愛彦 (2012). 神経ネットワークとグラフ理論 シンポジウム「応用脳科学研究の進展」早稲田大学応用脳科学研究所主催，早稲田大学，6月30日
 
- 国里愛彦 (2012). うつ病と意思決定：計算論的臨床心理学からみたうつ病　 シンポジウム「不安、うつ、妄想に挑む心理学：臨床と基礎の融合を目指して」専修大学社会知性開発研究センター／心理科学研究センター主催，専修大学，6月16日
 
 <iframe src="//www.slideshare.net/slideshow/embed_code/key/jW5PRFuYmHDHm8" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-74207031" title="うつ病と意思決定" target="_blank">うつ病と意思決定</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>

- 国里愛彦 (2012). 脳画像による特性マーカー研究は心理臨床に寄与するのか？-安静時fMRIと構造体積研究からの挑戦- 研究会「基礎と臨床をつなぐ会」，早稲田大学，3月24日
 
- 国里愛彦 (2012). 機能画像研究における特性マーカー：安静時fMRIとVBMを用いて 研究会「精神神経内分泌免疫学研究会　第15回研究集会」，独立行政法人産業技術総合研究所　臨海副都心センター，1月7日
 
## 2011
### ポスター発表

- [41] 横山仁史・野田隆政・小関俊祐・国里愛彦・伊藤大輔・巣山晴菜・杉村有司・石原奈保子・清水悠・中澤佳奈子・鈴木伸一(2011).　自動思考と客観的および主観的鬱症状との関連：多チャンネルNIRSを用いた検討　日本行動療法学会第37回大会　東京　2011年11月28日（プログラム集p.480-481）
 
- [40] 髙垣耕企・岡島義・国里愛彦・中島俊・坂野雄二(2011).　長期的な結果を予測した行動選択が回避行動に与える影響の検討　日本行動療法学会第37回大会　東京　2011年11月27日（プログラム集p.322-323）
 
- [39] 岡山紀子・清水馨・田上明日香・伊藤大輔・巣山晴菜・横山仁史・国里愛彦・鈴木伸一(2011).　職場サポート要因におけるメンタルヘルスへの影響性の検討　日本行動療法学会第37回大会　東京　2011年11月27日（プログラム集p.188-189）
 
- [38] 宣聖美・清水馨・田上明日香・伊藤大輔・巣山晴菜・横山仁史・国里愛彦・鈴木伸一(2011).　職場における個人要因がうつ症状に及ぼす影響　日本行動療法学会第37回大会　東京　2011年11月27日（プログラム集p.186-187）
 
- [37] 国里愛彦(2011). 行動活性化／行動抑制システムと安静時の自発的な脳活動との関連：安静時 fMRI を用いたデフォルトモードネットワークの観点から　パーソナリティ心理学会第20回大会　京都　2011年9月４日　(プログラム集p.23)
 
- [36] 髙垣耕企・岡島　義・国里愛彦・中島　俊・金井嘉宏・石川信一・坂野雄二(2011).　回避行動と行動活性から示される行動的特徴と抑うつ症状との関連　第8回日本うつ病学会総会 大阪　2011年　(p.164)
 
### 口頭発表・シンポジウム・研究会

- 国里愛彦(2011). 中級者による初心者のための「二変量解析の検定力分析」 研究会「心理・医学系研究者のためのデータ解析環境Rによる統計学の研究会」，東京医科歯科大学，11月5日

 <iframe src="//www.slideshare.net/slideshow/embed_code/key/rCOW5ypwm1x9cg" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/YoshihikoKunisato/ss-74207234" title="統計的検定と例数設計の基礎" target="_blank">統計的検定と例数設計の基礎</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/YoshihikoKunisato">Senshu University</a></strong> </div>
 
- [35] 国里愛彦(2011).寛解うつ病の脳機能画像研究 ワークショップ「うつ病寛解者における認知機能障害：基礎的知見と臨床実践からの展望」（山本哲也，嶋田洋徳，北川信樹，田上明日香，国里愛彦，池淵恵美）日本心理学会第75回大会，日本大学，9月15日
 
- 国里愛彦(2011).私の研究領域の「線形混合モデル」 研究会「心理・医学系研究者のためのデータ解析環境Rによる統計学の研究会」，東京医科歯科大学，8月20日
 
## 2010
### ポスター発表

- [34] 国里愛彦・岡本泰昌・吉村普平・上田一貴・岡田　剛・松永美希・小野田慶一・鈴木伸一・山脇成人(2010).　右上側頭回体積が集団認知行動療法への治療反応性を予測する：Voxel based morphometryを用いた検討　第36回行動療法学会　名古屋　2010年
 
- [33] 岡島　義・国里愛彦・中島　俊・髙垣耕企(2010). うつ病に対する行動活性化法に関するメタ分析的レビュー 第36回行動療法学会　名古屋　2010年
 
- [32] 髙垣耕企・岡島　義・国里愛彦・中島　俊・金井嘉宏・石川信一・坂野雄二(2010).　行動的要因に注目した抑うつ気分の悪循環モデルの検討　第36回行動療法学会　名古屋　2010年
 
- [31] 国里愛彦・岡本泰昌・岡田剛・山脇成人(2010).　Big FiveモデルとDefault mode networkとの関連　-安静時fMRIを用いた検討- 日本パーソナリティ心理学会 第19回大会　東京　2010年 [優秀大会発表賞]
 
- [30] 髙垣耕企・岡島　義・国里愛彦・中島　俊・金井嘉宏・石川信一・坂野雄二(2010).　Behavioral Activation for Depression Scale（BADS）日本語版の作成　 第１０回認知療法学会　名古屋　2010年
 
- [29] 国里愛彦・岡田剛・青山志緒里・宗像 あゆみ・小野田 慶一・岡本泰昌・野村 理朗・山脇成人(2010).　セロトニン欠乏が遅延割引に及ぼす影響　第１０回認知療法学会　名古屋　2010年
 
- [28] 国里愛彦・青山志緒里・宗像あゆみ・小野田慶一 ・野村理朗(2010).　安静時脳活動に及ぼすセロトニン欠乏の効果 -Resting state fMRIによる検討- 日本心理学会第74回大会　大坂　2010年
 
- [27] 国里愛彦・岡本泰昌・岡田剛・青山志緒里・宗像 あゆみ・小野田 慶一・野村 理朗・山脇成人(2010). 安静時脳活動と衝動性に及ぼすセロトニン欠乏の効果　第15回認知神経科学会　松江　2010年
 
### 口頭発表・シンポジウム・研究会

- [26] 国里愛彦(2010). うつ病における行動活性化の実際と今後の展開 ワークショップ「行動活性化(3):研究と実践」 (国里愛彦[=企画者・話題提供者]，伊藤直，岡島義，高垣耕企，中島俊，鈴木伸一)　日本心理学会第74回大会，大阪大学，9月20～22日
 
 
## 2009
### ポスター発表

- [25] 小野田慶一・岡本泰昌・国里愛彦・岡田剛・山口修平・山脇成人(2009). 報酬予測における割引率と線条体の活動領域の関連　第14回認知神経科学会　東京　2009年
 
- [24] 松永美希・ 岡本泰昌・鈴木伸一・吉村晋平・国里愛彦・吉野敦雄・山脇成人(2009). 治療抵抗性うつ病に対する集団認知行動療法の効果：短期的効果と治療反応に関する検討　 第９回認知療法学会　千葉　2009年
 
- [23] 国里愛彦・上田一貴・小野田慶一・吉村晋平・鈴木伸一・岡本泰昌・山脇成人(2009).　抑うつと報酬・罰に対する感受性:強化学習モデルを用いた検討（２）　第９回認知療法学会　千葉　2009年
 
- [22] 吉村晋平・岡本泰昌・吉野敦雄・国里愛彦・小野田慶一・山脇成人(2009).　認知的制御による予期不安の低下に関わる脳機能の検討　 第９回認知療法学会　千葉　2009年
 
- [21] 国里愛彦・上田一貴・小野田慶一・吉村晋平・鈴木伸一(2009).　抑うつと報酬・罰に対する感受性-強化学習モデルを用いた検討- 　日本心理学会第73回大会　京都　2009年
 
- [20] 吉村晋平・岡本泰昌・小野田慶一・松永美希・国里愛彦・上田一貴・鈴木伸一・山脇成人(2009). 情動処理と関連する脳機能と認知行動療法の影響について:うつ病患者を対象にしたfMRI研究　第６回日本うつ病学会　東京　2009年　[学会奨励賞]
 
### 口頭発表・シンポジウム・研究会

- [19] 国里愛彦 (2009). 抑うつと報酬・罰への感受性-強化学習理論を用いた検討- ワークショップ「うつ病の脳機能画像研究の臨床実践への応用可能性 」 (国里愛彦[=企画者・話題提供者]，吉村晋平，上田一貴，小野田慶一，杉浦義典)　日本心理学会第73回大会，立命館大学，8月26～28日
 
- [18] 国里愛彦 (2009). エクササイズと行動活性化 ワークショップ「行動活性化(2):意義と新たな展開」 (国里愛彦[=企画者・話題提供者]，岡島義，高垣耕企，中島俊，大河内 浩人，岡本 泰昌)　日本心理学会第73回大会，立命館大学，8月26～28日
 

## 2008
### ポスター発表

- [17] 国里愛彦・浅本有美・伊藤大輔・鈴木伸一(2008).　項目反応理論による心理的ストレス反応尺度の検討:段階反応モデルによる検討　日本行動療法学会第34回大会　東京　2008年
 
- [16] 国里愛彦・淡野将太・山口陽弘・鈴木伸一(2008).　 項目反応理論による日本語版BIS/BAS尺度の検討 日本心理学会第72回大会　北海道　2008年
 
- [15] 伊藤大輔・国里愛彦・浅本有美・鈴木伸一(2008).　高校新入学時の特有のストレッサーがストレス反応に及ぼす影響－4ヵ月フォローアップによる継時的変化の検討－　日本心理学会第72回大会　北海道　2008年
 
### 口頭発表・シンポジウム・研究会

- [14] 国里愛彦(2008). 行動活性化に関する基礎研究 ワークショップ「行動活性化:理論的枠組みと臨床的利用」 (国里愛彦[=企画者・司会者・話題提供者]，岡島義，中島俊，原井宏明，松永美希，杉浦義典)　日本心理学会第72回大会，北海道大学，9月19～21日
 
## 2007
### ポスター発表

- [13] 浅本有美・国里愛彦・村岡洋子・堂谷知香子・在原理沙・田所健児・伊藤大輔・伊藤有里・佐々木美保・尾形明子・鈴木伸一(2007). 小学校低学年児童に対する集団SST－取り組みやすく、児童の動機づけを高める集団SSTプログラム－　日本行動療法学会第33回大会　兵庫　2007年
 
- [12] 村岡洋子・佐々木美保・浅本有美・在原理沙・堂谷知香子・田所健児・伊藤大輔・伊藤　有里・国里愛彦・尾形明子・鈴木伸一(2007).　小学校低学年児童に対す る集団SSTの効果の検討－訓練前の社会的スキルのレベルの違いに着目して－　日本行動療法学会第33回大会　兵庫　2007年
 
- [11] 山本友美子・国里愛彦・伊藤大輔・浅本有美・川人潤子・鈴木伸一(2007).　入学時のストレッサーと学校不適応との関連（５）－高校新入生ストレッサー尺度の信頼性・妥当性の検討－　日本行動療法学会第33回大会　兵庫　2007年
 
- [10] 川人潤子・国里愛彦・浅本有美・伊藤大輔・山本友美子・鈴木伸一(2007).　入学時のストレッサーと学校不適応との関連（４）－同一高等学校の学科差に着目して－　日本行動療法学会第33回大会　兵庫　2007年
 
- [9] 国里愛彦・上田一貴・鈴木伸一(2007).　報酬・罰への感受性と抑うつの関連－報酬・罰への感受性の個人内の組み合わせパターンに着目して－　日本行動療法学会第33回大会　兵庫　2007年
 
- [8] 伊藤大輔・佐藤健二・国里愛彦・浅本有美・鈴木伸一(2007). トラウマ開示によるトラウマ反応改善効果を媒介する要因の検討-トラウマ筆記内容のテキストマイニングによる言語解析-　日本心理学会第71回大会　東京　2007年
 
- [7] 浅本有美・国里愛彦・伊藤大輔・鈴木伸一(2007).　反芻と抑うつの関連－素因ストレスモデルの観点から－　日本心理学会第71回大会　東京　2007年
 
- [6] 国里愛彦・上田一貴・伊藤大輔・浅本有美・鈴木伸一(2007).　報酬・罰への敏感性と抑うつの関連－素因ストレスモデルの観点から－　日本心理学会第71回大会　東京　2007年

- [5] 山口陽弘・国里愛彦・大久保智紗(2007). TCIの下位尺度項目の検討-因子的妥当性の観点から-Ⅱ　日本教育心理学会第49回総会　東京　2007年
 
- [4] 長原啓三・国里愛彦・伊藤大輔・在原理沙・鈴木伸一(2007).　入学時のストレッサーと学校不適応との関連(2)-高校新入生ストレッサー尺度とストレス反応・学校享受感の関連-　日本教育心理学会第49回総会　東京　2007年
 
- [3] 国里愛彦・長原啓三・浅本有美・伊藤有里・鈴木伸一(2007).　入学時のストレッサーと学校不適応との関連(1)-高校新入生ストレッサー尺度の作成-　日本教育心理学会第49回総会　東京　2007年
 
## 2006
### ポスター発表

- [2] 山口陽弘・国里愛彦(2006). 　TCIの下位尺度項目の検討-因子的妥当性の観点から-　日本教育心理学会第48回総会　岡山　2006年

- [1] 国里愛彦・山口陽弘・鈴木伸一　TCIによるBig Five尺度の予測について　日本教育心理学会第48回総会　岡山　2006年