---
title: "研究室のメンバー"
---

### 教員

- [国里愛彦](yoshihiko-kunisato.html)

### 学振PD

- 募集中

### 大学院生（博士過程）

- 募集中

### 大学院生（修士２年）

- 藁科佳奈
- 村口ゆら

### 大学院生（修士１年）

- 大水拓海
- 松本有里菜

### 学部生（４年以上）

- 磯崎ほのか
- 鄭 雨薇
- 長谷川 林


### 学部生（３年）

- 狩谷瑠海
- 加藤めぐみ
- 大村めい
- 菅原 宙
- 高田琴未
- 皆川 彩

### OB・OG

### 2023年度

#### 学部

- 許　懐中(卒業論文題目「養育態度と抑うつとの関連における完全主義傾向の媒介効果の検討」)
- 鈴木あまね(卒業論文題目「反すうが悲しい気分時の音楽選択にあたえる影響」)
- 山岸隆次(卒業論文題目「会話成立場面における原因帰属傾向と自己効力感との関連および自己へのゆるし傾向性との関連」)
- 大水拓海(卒業論文題目「複雑系としてのうつ病の症状維持と治療作用メカニズム　―ネットワークモデルを用いた数理シミュレーションによる検討ー」)
- 平井将登(卒業論文題目「不安・緊張場面でのスポーツパフォーマンスとイメージ明瞭度の関連」)
- 田島くるみ(卒業論文題目「大学駅伝部における言葉がけが動機づけに与える影響」)
- 加藤日和(卒業論文題目「ストレッサーの種類によるレジリエンスの調整効果がストレス反応に与える影響」)

#### 修士

- 小幡真優(修士論文題目「うつ病休職者に対するスティグマと組織風土の関連」)
- 甲斐亜祐璃(修士論文題目「反すうの数理シミュレーション」)

#### PD

- [遠山朝子](https://researchmap.jp/aaa911) (学術振興会特別研究員PD ➟ 一橋大学）

### 2022年度
#### 学部

- 小嶺幸司(卒業論文題目「援助利益の促進による援助要請の促進研究」)
- 藁科佳奈(卒業論文題目「パニック症に対するリラクセーション法の作用の検討ー数理モデルを用いたシミュレーションによる検討ー」)
- 隅田昌孝(卒業論文題目「社交不安症の認知モデルに関する形式理論化の試み」)
- 村口ゆら(卒業論文題目「心理学的ネットワーク分析を用いたスポーツのパフォーマンスと情動の関係」)
- 岡野真由(卒業論文題目「PTSDによる持続エクスポージャー療法とEMDRの比較ーネットワークメタ分析による検討ー」)

#### 修士

- 齋藤裕希子(修士論文題目「内受容感覚への意味づけと関わり方の不安に対する影響」)

#### 博士

- 杣取恵太(博士論文題目「恐怖条件づけの獲得・消去にメタ認知が与える影響」)

### 2021年度
#### 学部

- 澤村直樹(卒業論文題目「匿名の相手から否定的なリプライを受けたときの不快度とソーシャルスキル、及びコーピング採用パターンとの関連」)
- 朱延盛(卒業論文題目「主観的ウェルビーイングの計算論的モデルの東アジアおける検討」)

#### 修士

- 山崎　智(修士論文題目「新たな心理的柔軟性尺度の開発とセルフ・コンパッションとの関連     −COSMINと心理ネットワークモデルを用いた検討−」)　
- 井上圭右(修士論文題目「社交不安と解釈バイアスの心理学的ネットワークの関連」)　


### 2020年度
#### 学部

- 齋藤裕希子 (卒業論文題目「心理学的ネットワーク解析を用いた内受容感覚及び不安や抑うつとの関係の検討」)
- ウ ジヒ (卒業論文題目「自己複雑性と抑うつの関連についてのメタ分析：文化差の検討」)
- 田中遼太 (卒業論文題目「社交不安に対する注意バイアス修正の効果に対するメタ分析―文化差に注目して―」)
- 五十嵐大知 (卒業論文題目「心理学的ネットワーク解析を用いた社交不安症と対人恐怖症の比較」)

### 2019年度
#### 学部

- 菊池流那
- 柴田真衣
- 柴谷桃佳
- 井上のどか
- 井上幸奈
- 大房夏海
- 鈴木海渡

※国里が在外研究中（アムステルダム大学）だったため，2019年度のゼミは，帝京大学の飯島雄大先生にご指導いただきました。

### 2018年度
#### 学部

- 阿久津裕史(卒業論文題目「感情への恐れがマインドフルネス特性及びひきこもり親和性に与える影響について」）
- 広瀬友彩(卒業論文題目「妬みのサブタイプとセルフ・コンパッション及びネガティブ感情の関連」) 
- 小嶋那奈(卒業論文題目「課題解決場面における防衛的悲観主義者の他者サポートについての検討」) 
- アン ミョンヒ(卒業論文題目「日韓比較を通した養育態度が強迫傾向に影響するプロセスの検討:パーソナリティの媒介効果の検討」) 
- 井上圭右(卒業論文題目「社交不安と心的イメージとの関連: 認知課題を用いた検討」)
- 小澤千尋(卒業論文題目「感情価を伴う写真刺激の呈示による課題価値割引における先延ばしの変化」)
- 西田千夏(卒業論文題目「メランコリー親和型性格とコーピング及びサポート模索の関連」)

#### 修士
- 井口聖香(修士論文題目「過剰適応者の感情抑制」) 
- 土原浩平(修士論文題目「マインドフルネス特性と痛みの関連」) 


### 2017年度
#### 学部

- 福地友輔(卒業論文題目「重要他者に対する再確認傾向と表情認知及び不安の関連」） 
- 関 海真(卒業論文題目「曖昧さへの態度と思考抑制が強迫傾向に与える影響について」） 
- 中川卓知(卒業論文題目「抑うつとリスクテイキング行動との関連: Automatic BARTにおけるベイジアン認知モデリングの適応」）
- 中西由紀奈(卒業論文題目「社交不安症と対人恐怖症の比較: 自己主体感と友人関係への動機づけとの関連の検討」） 
- 長尾雅春(卒業論文題目「アプリ課金依存の類型と実体」） 
- 関谷朋志


#### 修士

- 金子美帆 (修士論文題目「反実仮想思考を用いた先延ばし行動低減プログラムの効果の検討」）
- 菊池羽音 (修士論文題目「外傷後認知の時系列的変化と症状・個人差要因との関連―トラウマフィルムパラダイムと経験サンプリング法による測定―」） 
- 土谷美月 (修士論文題目「不確実さ不耐性と条件づけ場所嗜好性の関連-強化率の操作とvirtual realityを用いた検討-」）

#### 博士2年

- 坂本次郎　(日本学術振興会 特別研究員DC1 ➟ 就職）

#### PD

- 森 正樹　(日本学術振興会 特別研究員PD ➟ 就職）


### 2016年度

#### 学部

- 山本由佳(卒業論文題目「対人場面における認知的方略の違いと抑うつの関連」） 
- 村越祐也(卒業論文題目「行動活性化, パーソナリティ特性,抑うつとの関連について-行動活性化の抑うつ低減効果にパーソナリティ特性がおよぼす影響-」） 
- 金子　瑶(卒業論文題目「悲しみ喚起場面における抑うつの時間的変化に対する反芻・省察の影響」） 
- 荒井遼河(卒業論文題目「完全主義が誘発する抑うつ傾向へのストレスマインドセットの調整効果の検討」） 
- 岡本亮平(卒業論文題目「抑うつを伝染しやすい人の特徴について-抑うつ伝染尺度の作成と対人依存・感情制御との関連の検討-」）
- 井口聖香(卒業論文題目「シャーデンフロイデと共感性の関連」） 
- 上田直人(卒業論文題目「サイコパシー傾向者の罰行動に伴うコストに対する飲酒の習慣の影響について」）

#### 修士

- 小田島裕佳(修士論文題目「社交不安傾向と空間周波数の低い表情画像に対する回避との関連」） 


### 2015年度

#### 学部

- 仁添未亜(卒業論文題目「イメージの視点と対人不安・抑うつの関連: 公的自己意識と不快情動喚起状況におけるイメージの内的・外的視点の観点から」）
- 大場広貴(卒業論文題目「拒絶に対する過敏性と社交不安が抑うつに及ぼす影響: ソーシャルサポートの影響による緩衝効果の観点から」）
- 井上ゆかり(卒業論文題目「シナリオが惹起する妬みに認知的負荷が及ぼす影響」）
- 土谷美月(卒業論文題目「スチューデント・アパシーと認知コントロールの関連: -切替情動ストループを用いて」）
- 金子美帆(卒業論文題目「価値割引パラダイムを用いた先延ばしの測定: 回避・衝動性の観点から」）
- 土舘佳子(卒業論文題目「肯定的・否定的自己複雑性と自己受容、問題解決能力との関連」）

#### 修士

- 坂本次郎(修士論文題目「抑うつと痛みの将来予測: 階層ベイズモデルによる意思決定の検討」）
- 杣取恵太(修士論文題目「メタ認知が恐怖条件づけの獲得・消去プロセスに与える影響: ベイジアン認知モデリングによる潜在過程の推定」）
- 時田椋子(修士論文題目「生態学的経時的評価法を用いた喫煙と渇望の関係: マインドフルネスの調整効果の観点から」）

### 2014年度

#### 学部

- 古川颯人(卒業論文題目「マインドワンダリングと創造性の研究」)
- 齊藤夏希(卒業論文題目「睡眠における注意訓練の効果」)
- 畑中勇人(卒業論文題目「マインドワンダリングとマインドフルネス特性の関係性」)

#### 修士

- 鈴木彩夏(修士論文題目「妬み感情と情動制御方略の関連 −Grossの情動制御プロセスモデルを用いて−」)

### 2013年度

#### 学部

- 上野駿介(卒業論文題目「火のある風景描画法による攻撃性へのカタルシス効果の検討」)
- 鬼澤詩織(卒業論文題目「家族関係単純図式投影法に表わされるきょうだい関係」)
- 道口尚弥(卒業論文題目「親密度の異なる対人場面における自他への攻撃性と自己愛傾向の関連について の検討」)
- 加瀬左緒里(卒業論文題目「大学生における対人恐怖心性と劣等感が生きがい感に及ぼす影響」)
- 兼松太郎(卒業論文題目「バウム・テストの空間使用量と Jung のタイプ論の検討」)