---
title: "movie"
author: "Yoshihiko Kunisato"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6.1.0/css/jspsych.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r}
library(htmltools)
tagList(
tags$script(src='jspsych-6.1.0/jspsych.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-video-slider-response.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-survey-multi-select.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-fullscreen_jp.js')
)
```

```{js}
var ic = {
    type: 'survey-multi-select',
    questions: [{
        prompt: '<span style = "font-size: 14pt"><b>以上の内容をよく読んで，理解した上で実験参加に同意いただける方はチェックをお願いします。同意されない方は，ウィンドウを閉じてください。</b></span>',
        options: ['<span style = "font-size: 14pt">説明事項をよく読み，理解した上で，研究参加に同意します。</span>'],
        required: true,
        name: 'approval'
    }],
    preamble: '<div style = "font-size: 14pt; text-align: left;"><p>A大学B部C学科・Dが行っている「Eに関する研究」に関心を持っていただき，誠にありがとうございます。参加にあたり，以下の説明をスクロールしてお読みください。</p>' +
    '<p><b>１．研究目的</b>' +
    '<br>本研究は，...を目的としております。</p>' +
    '<p><b>２．研究内容</b>' +
    '<br>本研究は，日本語を母国語とする20歳以上の方を対象としています。本研究では，...<参加者が取り組む内容を記載>...分程度で終了します。なお，これから行うアンケートや課題は，あなた個人の性格や能力を個別に評価することを目的とはしておりません。' +
    '<p><b>３．危険性ならびに不利益</b>' +
    '<br>研究に参加することで被る身体的な負担は，...。アンケートへの回答や課題中，もし不快感を感じることがあったら，ご自身の意志で研究参加をいつでも中止することができます。参加の中止はいつ，いかなる理由でも可能です。また，参加の中止，不参加に伴う不利益は一切生じません。</p>' +
    '<p><b>４．参加者の権利</b>' +
    '<br>本研究の参加は，皆様の自由意志によるものです。本研究に参加することに同意しても，それはいつでも撤回することができます。同意を撤回しても，いかなる不利益を受けることはありません。参加に同意した後に，参加途中で撤回する場合は，そのままウェブブラウザを閉じていただけると同意撤回したとみなします。参加途中で参加を撤回された場合は，そのデータをその後の研究で使用いたしません。また，最後まで参加したもののご自身の研究データを研究に使用してほしくない場合は，最後に提示されるコードを以下の連絡先にお送りいただければ，その後の研究でそのデータを使用いたしません。</p>' +
    '<p><b>5.謝礼</b>' +
    '<br>謝礼につきましては...。</p>' +
    '<p><b>6.研究結果の使用およびプライバシーの保護</b>' +
    '<br>参加された方のアンケートへの回答や課題への反応は，全て匿名で扱われ，データからあなたが特定されることはありません。本研究の結果は，学術論文や学会発表などを通じて公表される可能性があります。ただし，その際も参加者の代表値(平均値など)となる統計量を使用し，特定の個人に焦点を当てた発表は行いません。' +
    '<br>なお，この研究参加にあたり，画面上に呈示する画像などを皆様のパソコンに一時的にダウンロードします。最後まで研究に参加いただいた場合は，ダウンロードしたファイルは削除し，反応などのデータのみを取得します。その他の情報には一切アクセスいたしません。予めご了承ください。</p>' +
    '<p><b>7.データの公開</b>' +
    '<br>データを公開し広く閲覧・分析できる状態にすることは，研究の再現性を高め，今回の研究によって得られる知見の増加につながります。そのため，本研究では得られた研究データをAなどのサイトにおいて，公開することを予定しています。公開するのは，B,C,D,Eになります。その際，参加された際に付与されるIDとは全く別のIDをランダムに付与します。そのため，いかなる手段を用いても，公開データの閲覧者は，公開データから個人を特定することはできないようにいたします。</p>' +
    '<p><b>8.倫理委員会</b>' +
    '<br>本研究は，A大学B部C学科の人を対象とした研究倫理委員会の承認を得た上で実施しています（申請番号：E）。</p>' +
    '<p><b>9.研究結果のフィードバック方法</b>' +
    '<br>研究結果は，Aにて，B年C月D日からE年間フィードバックいたします。研究参加の辞退実験や本研究のお問い合わせは、以下の連絡先にお願い致します。</p>' +
    '<p><b>10.研究に関する問い合わせ先</b>' +
    '<br>A大学B部C学科 D' +
    '<br>〒214-8580 神奈川県川崎市多摩区東三田 2-1-1</p></div>',
    button_label: '次へ'
};

var instructions = {
  type: "html-keyboard-response",
  stimulus: "<p style='text-align:left'>これから動画が流れます。</p>"+
    "<p style='text-align'>流れている動画どのくらい好きか嫌いかマウスを使ってスライダーを動かして評価してください。</p>"+
    "<p style='text-align:left'>スペースを押して始めてください。</p>",
  post_trial_gap: 1000
};

var movie1 = {
    type: 'video-slider-response',
    sources:['video/v1.mp4'],
    width: 600,
    labels: ["1嫌い","2","3","4","5","6","7","8","9","10好き"],
    prompt: "<p>この動画がどのくらい好きか嫌いか，マウスでスライダーを動かして，評定してください</p>",
    button_label: "次へ"
}

var movie2 = {
    type: 'video-slider-response',
    sources:['video/v2.mp4'],
    width: 600,
    labels: ["1嫌い","2","3","4","5","6","7","8","9","10好き"],
    prompt: "<p>この動画がどのくらい好きか嫌いか，マウスでスライダーを動かして，評定してください</p>",
    button_label: "次へ"
}

var timeline = [];
timeline.push(ic);
timeline.push({
  type: 'fullscreen',
  fullscreen_mode: true
});
timeline.push(instructions);
timeline.push(movie1);
timeline.push(movie2);

jsPsych.init({
    timeline: timeline,
    on_finish: function() {
     jsPsych.data.displayData();
    }
});
```
