---
title: "Hello"
author: "Yoshihiko Kunisato"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6.1.0/css/jspsych.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(htmltools)
tagList(
tags$script(src='jspsych-6.1.0/jspsych.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-html-keyboard-response.js')
)
```

```{js}
    /* タイムラインを用意 */
    var timeline = [];
    /* 呈示する文字を変数にする */
    var text = ["こんにちは","ニイハオ","アニョハセヨ","ハロー"]
    /* trialで呈示する文字を設定 配列[0] */
    var welcome = {
      type: "html-keyboard-response",
      stimulus: text[0],
      trial_duration: 1000
    };
    timeline.push(welcome);
    /* trialで呈示する文字を設定 配列[1]*/
    var welcome = {
      type: "html-keyboard-response",
      stimulus: text[1],
      trial_duration: 1000
    };
    timeline.push(welcome);
    /* trialで呈示する文字を設定 配列[2]*/
    var welcome = {
      type: "html-keyboard-response",
      stimulus: text[2],
      trial_duration: 1000
    };
    timeline.push(welcome);
    /* trialで呈示する文字を設定 配列[3]*/
    var welcome = {
      type: "html-keyboard-response",
      stimulus: text[3],
      trial_duration: 1000
    };
    timeline.push(welcome);
    /* 実験開始 */
    jsPsych.init({
      timeline: timeline
    });
```
