---
title: "audio"
author: "Yoshihiko Kunisato"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6.1.0/css/jspsych.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r}
library(htmltools)
tagList(
tags$script(src='jspsych-6.1.0/jspsych.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='jspsych-6.1.0/plugins/jspsych-audio-keyboard-response.js')
)
```

```{js}
var instructions = {
  type: "html-keyboard-response",
  stimulus: "<p style='text-align:left'>これから百人一首の音声が流れます。</p>"+
    "<p style='text-align'>流れているものを１から４のキーを押して選んでください。</p>"+
    "<p style='text-align:left'>スペースを押して始めてください。</p>",
  post_trial_gap: 1000
};

var hundred_poems1  = {
    type: 'audio-keyboard-response',
    stimulus: 'audio/a1.m4a',
    choices: ['1', '2','3','4'],
    prompt: "<p style='text-align:left'>これから流れる百人一首は以下のどれでしょうか？１から４のキーで選んでください</p>"+
    "<p style='text-align:left'>1 あしびきの山鳥の尾のしだり尾の　ながながし夜をひとりかも寝む</p>"+
    "<p style='text-align:left'>2 春過ぎて夏来にけらし白妙の　衣干すてふ天の香具山</p>"+
    "<p style='text-align:left'>3 秋の田のかりほの庵の苫をあらみ　わが衣手は露にぬれつつ</p>"+
    "<p style='text-align:left'>4 田子の浦にうち出でてみれば白妙の　富士の高嶺に雪は降りつつ</p>"
};

var hundred_poems2  = {
    type: 'audio-keyboard-response',
    stimulus: 'audio/a2.m4a',
    choices: ['1', '2','3','4'],
    prompt: "<p style='text-align:left'>これから流れる百人一首は以下のどれでしょうか？１から４のキーで選んでください</p>"+
    "<p style='text-align:left'>1 かささぎの渡せる橋に置く霜の　白きを見れば夜ぞ更けにける</p>"+
    "<p style='text-align:left'>2 わが庵は都の辰巳しかぞ住む　世をうぢ山と人はいふなり</p>"+
    "<p style='text-align:left'>3 天の原ふりさけみれば春日なる　三笠の山に出でし月かも</p>"+
    "<p style='text-align:left'>4 奥山に紅葉踏み分け鳴く鹿の　声聞く時ぞ秋は悲しき</p>"
};

var timeline = [];
timeline.push(instructions);
timeline.push(hundred_poems1);
timeline.push(hundred_poems2);

jsPsych.init({
    timeline: timeline,
    on_finish: function() {
     jsPsych.data.displayData();
    }
});
```
